### ISSUE TITLE
Add capability to initiate live stream

### ISSUE THREAD

**Issue by jasperpants** [gopro/OpenGoPro#10]
Would it be possible to implement commands to have the camera connect to wifi and begin a livestream via RTMP, Facebook etc?

**Comment by hpwd** [comment]
I need this so much

**Comment by KonradIT** [comment]
To shine some light:

I think this is done first by issuing the WiFi creds over to char `0x39` (settings). They basically do the inverse of https://gopro.github.io/OpenGoPro/ble#get-hardware-info for sending the data.

[0x39 20 28...]

[0x39 80 34...]

[0x39 81 34...]

Then the actual stream gets sent over 0x2F 

[0x2F 20 48...]

[0x2F 80 61....]

**Comment by h0peixoto** [comment]
> To shine some light:
> 
> I think this is done first by issuing the WiFi creds over to char `0x39` (settings). They basically do the inverse of https://gopro.github.io/OpenGoPro/ble#get-hardware-info for sending the data.
> 
> [0x39 20 28...]
> 
> [0x39 80 34...]
> 
> [0x39 81 34...]
> 
> Then the actual stream gets sent over 0x2F
> 
> [0x2F 20 48...]
> 
> [0x2F 80 61....]

Have you tried this bro ?

**Comment by zsinba** [comment]
I need this so much

**Comment by tcamise-gpsw** [comment]
Hi. This is now possible and defined in the BLE [spec](https://gopro.github.io/OpenGoPro/ble_2_0#live-streaming)
