### ISSUE TITLE
Error if '-' in nmcli driver version name

### ISSUE THREAD

**Issue by pavloshargan** [gopro/OpenGoPro#107]
This bug is in python sdk

**To Reproduce**
This error occurs if your nmcli driver version name has  '-' symbol. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26502150/147761377-86e9e94a-d8ff-48e3-a286-cb0419a22b8d.png)

![image](https://user-images.githubusercontent.com/26502150/147761126-26b7bdaf-7ab9-4d17-ae50-cf7859d0a453.png)
I solved it with replacing the '-' to '.':
![image](https://user-images.githubusercontent.com/26502150/147761241-d98fd7a8-c7e8-4cd6-9d66-18f57065c61b.png)

**Comment by tcamise-gpsw** [comment]
This should be fixed as part of #108 by using `distutils.version.LooseVersion` to handle the version comparison
