### ISSUE TITLE
Space in Gopro AP ssid fails the connection

### ISSUE THREAD

**Issue by pavloshargan** [gopro/OpenGoPro#119]
Bug in  Demos (python sdk, etc)

 Nmcli command fails connecting to the GoPro AP, if the Gopro ssid contains spaces

![image](https://user-images.githubusercontent.com/26502150/151390685-1b007ff5-4b35-46a8-8a6b-be7e8bbce104.png)

fixed adding the quotes to the command: (OpenGoPro/demos/python/sdk_wireless_camera_control/open_gopro/wifi/adapters/wireless.py line 408 class: Nmcli0990Wireless, method: connect)

```
nmcli dev wifi connect \"{ssid}\" password {password} ifname {self._interface}
```

![image](https://user-images.githubusercontent.com/26502150/151390962-d91c0e2e-c1d5-4c81-9c7d-39a26af5eebd.png)

Suppose this issue could happen using other drivers classes as well

**Comment by tcamise-gpsw** [comment]
Hello. Thanks for pointing this out. I'm in the middle of updating that Wifi driver so will add this and test it out.

**Comment by tcamise-gpsw** [comment]
This has been fixed on main but not yet published to PyPi
