### ISSUE TITLE
How to delete media

### ISSUE THREAD

**Issue by LightCannon** [gopro/OpenGoPro#139]
Hello. Thanks for this project. I would like to know is there a way to delete a media from the storage? I can see I can download media using wifi commands. However, I see no api for deleting media using the Python API. 
Is there a way to achieve this? 
Regards.

**Comment by tcamise-gpsw** [comment]
Hi. There is currently no way to do this. It is possible that it will be documented for a future release.

Closing this since it is being tracked in #74

**Comment by aallaire91** [comment]
This works for me in the meantime.

        file="GX010021.MP4"
        url = GOPRO_BASE_URL[:-5] + "/gp/gpControl/command/storage/delete?p=" + "/100GOPRO/" + file
        # Send the GET request and retrieve the response
        with requests.get(url) as request:
            request.raise_for_status()        # Check for errors (if an error is found, an exception will be raised)

**Comment by tony-gutierrez** [comment]
Go pro 11:
https://github.com/gopro/OpenGoPro/issues/74#issuecomment-1680638161
