### ISSUE TITLE
I'd love to build an OpenGoPro project on VS for Mac 2019 ...

### ISSUE THREAD

**Issue by simspace-dev** [gopro/OpenGoPro#154]
I'd love to build a C# OpenGoPro project on VS for Mac 2019, but I can't build the sample apps.
Are you aware of any Mac OS samples I could try and build?
Thanks!

**Comment by tcamise-gpsw** [comment]
Hello. There are C# [demos ](https://gopro.github.io/OpenGoPro/demos#csharp) but unfortunately they are only supported on Windows.

I'm not very familiar with c# / .NET so can't speak to the feasibility of porting this to MacOS.
