### ISSUE TITLE
gopro-wifi throws exception on Mac OS

### ISSUE THREAD

**Issue by sven-ds** [gopro/OpenGoPro#156]
**Component**
What is the bug in?
- Demos (python sdk, etc)
gopro-wifi

**Describe the bug**
gopro-wifi throws an exception which looks like there's a protocol error communicating with the camera.

**To Reproduce**
1. Create fresh virtualenv
2. pip install open-gopro
3. Activate virtualenv
4. Call gopro-wifi

**Expected behavior**
The demo to run as described on the website

**Screenshots**

(research) ~❯ gopro-wifi
WARNING  17:41:48.007 Failed to find a device in 5 seconds. Retrying #1                                                                                             client.py:80
INFO     17:41:53.139 Establishing the BLE connection                                                                                                              client.py:102
INFO     17:41:54.243                                                                                                                                             builders.py:81

         <<<<<<<<--------------
                 register_value_update : StatusId.ENCODING
         <<<<<<<<--------------

INFO     17:41:54.272                                                                                                                                             builders.py:83

         -------------->>>>>>>>
         {
             "status": "SUCCESS",
             "id": "Query Response::QueryCmdId.REG_STATUS_VAL_UPDATE",
             "StatusId.ENCODING": false
         }
         -------------->>>>>>>>

INFO     17:41:54.275                                                                                                                                             builders.py:81

         <<<<<<<<--------------
                 register_value_update : StatusId.SYSTEM_READY
         <<<<<<<<--------------

INFO     17:41:54.303                                                                                                                                             builders.py:83

         -------------->>>>>>>>
         {
             "status": "SUCCESS",
             "id": "Query Response::QueryCmdId.REG_STATUS_VAL_UPDATE",
             "StatusId.SYSTEM_READY": true
         }
         -------------->>>>>>>>

INFO     17:41:54.325                                                                                                                                            builders.py:538

         <<<<<<<<--------------
                 Set LED: LED.BLE_KEEP_ALIVE
         <<<<<<<<--------------

INFO     17:41:54.325 BLE is ready!                                                                                                                                 gopro.py:501
INFO     17:41:54.328                                                                                                                                            builders.py:292

         <<<<<<<<--------------
                 GET_THIRD_PARTY_API_VERSION
         <<<<<<<<--------------

WARNING  17:41:54.363 Received non-success status: ErrorCode.ERROR                                                                                                  gopro.py:653
INFO     17:41:54.375                                                                                                                                            builders.py:549

         -------------->>>>>>>>
         {
             "status": "ERROR",
             "id": "Settings Response::SettingId.LED"
         }
         -------------->>>>>>>>

INFO     17:41:54.401                                                                                                                                            builders.py:538

         <<<<<<<<--------------
                 Set LED: LED.BLE_KEEP_ALIVE
         <<<<<<<<--------------

Exception in callback PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 3, bytes = 0x025102}, None)
handle: <Handle PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 3, bytes = 0x025102}, None)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/sven/env/research/lib/python3.8/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 365, in did_update_value_for_characteristic
    notify_callback(c_handle, bytearray(value))
  File "/Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py", line 524, in _notification_handler
    response._parse()
  File "/Users/sven/env/research/lib/python3.8/site-packages/open_gopro/responses.py", line 500, in _parse
    self.data = self._parsers[self.id].parse(buf)  # type: ignore
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 4101, in _parse
    stream_read(stream, pad, path)
  File "/Users/sven/env/research/lib/python3.8/site-packages/construct/core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing)
stream read less than specified amount, expected 1, found 0
ERROR    17:41:59.460 Response timeout of 5 seconds!                                                                                                                gopro.py:648
ERROR    17:41:59.465 Error while opening: Response timeout occurred of 5 seconds                                                                                   gopro.py:374
INFO     17:41:59.468 Terminating the BLE connection                                                                                                               client.py:126
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py:646 in                  │
│ _write_characteristic_receive_notification                                                       │
│                                                                                                  │
│   643 │   │   self._ble.write(uuid, data)                                                        │
│   644 │   │   # Wait to be notified that response was received                                   │
│   645 │   │   try:                                                                               │
│ ❱ 646 │   │   │   response: GoProResp = self._sync_resp_ready_q.get(timeout=WRITE_TIMEOUT)       │
│   647 │   │   except queue.Empty as e:                                                           │
│   648 │   │   │   logger.error(f"Response timeout of {WRITE_TIMEOUT} seconds!")                  │
│   649 │   │   │   raise ResponseTimeout(WRITE_TIMEOUT) from e                                    │
│ /usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/queue │
│ .py:178 in get                                                                                   │
│                                                                                                  │
│   175 │   │   │   │   while not self._qsize():                                                   │
│   176 │   │   │   │   │   remaining = endtime - time()                                           │
│   177 │   │   │   │   │   if remaining <= 0.0:                                                   │
│ ❱ 178 │   │   │   │   │   │   raise Empty                                                        │
│   179 │   │   │   │   │   self.not_empty.wait(remaining)                                         │
│   180 │   │   │   item = self._get()                                                             │
│   181 │   │   │   self.not_full.notify()                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Empty

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/sven/env/research/bin/gopro-wifi:8 in <module>                                            │
│                                                                                                  │
│   5 from open_gopro.demos.connect_wifi import main                                               │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/demos/connect_wifi.py:68 in main │
│                                                                                                  │
│   65 │   gopro: Optional[GoPro] = None                                                           │
│   66 │   return_code = 0                                                                         │
│   67 │   try:                                                                                    │
│ ❱ 68 │   │   with GoPro(identifier, wifi_interface=wifi_interface):                              │
│   69 │   │   │   # Now we only want errors                                                       │
│   70 │   │   │   set_logging_level(logger, logging.ERROR)                                        │
│   71                                                                                             │
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py:214 in __enter__        │
│                                                                                                  │
│   211 │   │   │   self._state_thread = threading.Thread(target=self._maintain_state, name="sta   │
│   212 │                                                                                          │
│   213 │   def __enter__(self) -> "GoPro":  # pylint: disable=missing-return-doc                  │
│ ❱ 214 │   │   self.open()                                                                        │
│   215 │   │   return self                                                                        │
│   216 │                                                                                          │
│   217 │   def __exit__(self, *_: Any) -> None:                                                   │
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py:376 in open             │
│                                                                                                  │
│   373 │   │   except Exception as e:                                                             │
│   374 │   │   │   logger.error(f"Error while opening: {e}")                                      │
│   375 │   │   │   self.close()                                                                   │
│ ❱ 376 │   │   │   raise e                                                                        │
│   377 │                                                                                          │
│   378 │   def close(self) -> None:                                                               │
│   379 │   │   """Safely stop the GoPro instance.                                                 │
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py:360 in open             │
│                                                                                                  │
│   357 │   │   │   self._open_ble(timeout, retries)                                               │
│   358 │   │   │                                                                                  │
│   359 │   │   │   # Find and configure API version                                               │
│ ❱ 360 │   │   │   version = self.ble_command.get_open_gopro_api_version().flatten                │
│   361 │   │   │   version_str = f"{version.major}.{version.minor}"                               │
│   362 │   │   │   if version_str != "2.0":                                                       │
│   363 │   │   │   │   raise InvalidOpenGoProVersion(version)                                     │
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/api/builders.py:297 in __call__  │
│                                                                                                  │
│   294 │   │   data = bytearray([self.cmd.value])                                                 │
│   295 │   │   data.insert(0, len(data))                                                          │
│   296 │   │   # Send the data and receive the response                                           │
│ ❱ 297 │   │   response = self.communicator._write_characteristic_receive_notification(self.uui   │
│   298 │   │   logger.info(build_log_rx_str(response))                                            │
│   299 │   │   return response                                                                    │
│   300                                                                                            │
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py:69 in wrapper           │
│                                                                                                  │
│    66 │   │   │   raise GoProNotInitialized("BLE not connected")                                 │
│    67 │   │   if interface is Interface.WIFI and not instance.is_wifi_connected:                 │
│    68 │   │   │   raise GoProNotInitialized("Wifi not connected")                                │
│ ❱  69 │   │   return wrapped(*args, **kwargs)                                                    │
│    70 │                                                                                          │
│    71 │   return wrapper                                                                         │
│    72                                                                                            │
│                                                                                                  │
│ /Users/sven/env/research/lib/python3.8/site-packages/open_gopro/gopro.py:649 in                  │
│ _write_characteristic_receive_notification                                                       │
│                                                                                                  │
│   646 │   │   │   response: GoProResp = self._sync_resp_ready_q.get(timeout=WRITE_TIMEOUT)       │
│   647 │   │   except queue.Empty as e:                                                           │
│   648 │   │   │   logger.error(f"Response timeout of {WRITE_TIMEOUT} seconds!")                  │
│ ❱ 649 │   │   │   raise ResponseTimeout(WRITE_TIMEOUT) from e                                    │
│   650 │   │                                                                                      │
│   651 │   │   # Check status                                                                     │
│   652 │   │   if not response.is_ok:                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ResponseTimeout: Response timeout occurred of 5 seconds

**Hardware**
- Camera: Hero8
- Desktop if applicable: Mac OS 12.2.1, Python 3.8

**Additional context**
The script output looks like the first communication with the camera is successful, but then a command is not recognized by the camera and an error is sent back, causing an exception to be raised.

**Comment by tcamise-gpsw** [comment]
Hello. It's a little hard to say because the format of the log got screwed up when you pasted it but it looks like you are getting  `InvalidOpenGoProVersion(version)` exception.

This is expected since you are using a Hero 8 which is not one of the cameras supported via the [Open GoPro API](https://gopro.github.io/OpenGoPro/ble_2_0#supported-cameras)

As a side note, this exception output should be once nicer once #121  is closed
