### ISSUE TITLE
Support for GoPro MAX

### ISSUE THREAD

**Issue by McC0dy** [gopro/OpenGoPro#160]
**Is your feature request related to a problem or use case? Please describe.**
I want to use OpenGoPro for interacting with my GoPro MAX and future GoPro 360-cameras but only GoPro HERO9 and HERO10 is listed as supported. When will GoPro MAX be supported officially/ unofficially? How about future 360 cameras?

**Describe the solution you'd like**
Support for GoPro MAX and relevant documentation.

**Describe alternatives you've considered**
None, since my application uses 360 cameras and MAX is the only GoPro available.

**Comment by KonradIT** [comment]
It's supported unofficially by me.

https://github.com/konradit/goprowifihack

https://github.com/konradit/gopro-ble-py

https://github.com/konradit/gopro-py-api

**Comment by dzentech** [comment]
Hello!
It would also be cool to get control of the GoPro MAX via USB. That would be the best solution for stationary shooting. At the moment, the wifi connection is often not the most stable. A direct usb connection would solve all problems. Is there any such update planned for the camera?

**Comment by KonradIT** [comment]
Very unlikely GoPro MAX gets any FW update at all these days, let alone one that adds a completely new feature.

**Comment by martincarapia** [comment]
Does anyone know if this is now supported? I see the commit that referenced the issue but I'm not entirely sure if it's supported. I tried it myself with the python SDK but it seems it's under maintenance right now. Thanks!

**Comment by tcamise-gpsw** [comment]
@martincarapia No GoPro Max is not supported by Open GoPro.
That link to the commit is not accurate. It's taking a pull request number from an internal commit message that was included in an external push. Anyway just ignore it

**Comment by tcamise-gpsw** [comment]
Closing as this shall never be supported officially here.
