### ISSUE TITLE
Hi, about gopro license

### ISSUE THREAD

**Issue by khangzxrr** [gopro/OpenGoPro#167]
Hi I create an app to control gopro on iOS, but apple want to prove that I have license to publish my app meanwhile i'm using openGoPro open source... 
Can you give me any hint? thank you

Sorry if I posted on wrong site, I know this is github but i have no where to ask about this question

**Comment by KonradIT** [comment]
@rhoenschrat might have an idea how.

**Comment by khangzxrr** [comment]
Hi guys, my app just published. I don't know why and how. I just proved opengopro URL as many time as before but this time it worked!

**Comment by rhoenschrat** [comment]
@khangzxrr do you have a link to your app?
