### ISSUE TITLE
command/setup/date_time API gives 500 response code

### ISSUE THREAD

**Issue by harshmdr-devslane** [gopro/OpenGoPro#169]
**Api Response**
{"version": "6.00","path_info": "command/setup/date_time","query_string": "p=%16%05%05%0665","error_code":-3,"error_msg": "500 Internal Server Error","function": "gpcontrol_cgi_handler","line": 190}

**Hardware**
- Camera: Hero8 Black.

**Comment by tcamise-gpsw** [comment]
Hello. I'm not sure where you're getting that API from. Here is the relevant documentation from the Open GoPro 2.0 [quick reference](https://gopro.github.io/OpenGoPro/http_2_0#commands-quick-reference):

![image](https://user-images.githubusercontent.com/76070353/168915995-c6713146-9079-4078-a2b5-cd895c834221.png)

**Comment by tcamise-gpsw** [comment]
Closing since the supported command is working.
