### ISSUE TITLE
go pro max output original dual fisheye images

### ISSUE THREAD

**Issue by fushi219** [gopro/OpenGoPro#183]
**Is your feature request related to a problem or use case? Please describe.**
I would like to use the gopro max to do visual inertial odometry work, but the image frames in .360 file have already been converted to EAC format, so i wonder if there is a way to let the camera output original dual fisheye images(then i can calibrate the camera carefully)?

**Describe the solution you'd like**
If there is a API so i can make the camera to do not stitch images and directly output original dual fisheye images.
 
**Describe alternatives you've considered**
If no such api exists, how could i convert the EAC back into original fisheye format?

**Additional context**
No

**Comment by tcamise-gpsw** [comment]
Hello. GoPro Max is currently not supported in Open GoPro. An enhancement to track GoPro Max support already exists in #160. Feel free to add any comments there with desired features.
