### ISSUE TITLE
Camera stop response correctly gpMediaList after a timelapse

### ISSUE THREAD

**Issue by tcazes** [gopro/OpenGoPro#191]
Hi, i´m creating some integreation between python and Hero10. I use HTTP api over USB connection.  It´s works well, but in some cases, after some timelapse sequence, /gpMediaList method return a empty media vector. Even in the browser method return empy vector:

![image](https://user-images.githubusercontent.com/34246648/173707621-996c321c-d5f1-4f92-a555-6935ab40c715.png)

If i turnoff the camera and turn on it again, method respond correctly

![image](https://user-images.githubusercontent.com/34246648/173707777-7cb02162-ac6b-44ce-b580-9469e8255f22.png)

*ignore MP4 files here

After that, if i start another timelapse sequence the problem occour again. /gpMediaList stop to response until i restart camera.

In my project i need to start and stop timelapse photo, and keep monitoring all photos that was taken in near-real-time. Basicaly i do thats steps:

1. Call media list to get last media name (for last file name and last folder)
2. Start Time lapse photo (interval was setting in 0,5s)
3. Async call camera to check if predicted files was created ( i need to predict file name because getMediaList return busy when timelapse photo are taking and i need to give some feedbak along timelapse capture - it´s work very well)
4. Wait N seconds (i tried it for hours)
5. Finally method stop TimeLapse
6. Stop all asyn proccess

Along all steps and after that i have a list of all images taken withoud need to call /gpMediaList. That list are is incremented in real time. This is important for me.

I´m using a Hero10 Black. With firmware version H21.01.01.42.70 (Labs) connected by USB Cable

This problem can be related to LABfirmware? Has anyone ever experienced this?

Thanks for your help

**Comment by bfreeland-gpsw** [comment]
Hi @tcazes,

I'm working on investigating this and have a few questions:

1. What API call are you using on step 3 to determine whether the photo exists?
2. When in the steps do you call /gpMediaList?

If you just need to know the current progress of the timelapse while it is recording here's a workaround you can try while we investigate:

1. Query the state of the camera with /gopro/camera/state and store the total number of photos on the SD card (Status ID 38)
2. Start timelapse
3. Periodically query the state of the camera with /gopro/camera/state and subtract the value recorded in step 1 from the total number of photos on the SD card (Status ID 38) to get the current number of photos created by the timelapse

**Comment by pavlosharhan2** [comment]
@tcazes  Did you manage to resolve the problem?
