### ISSUE TITLE
Attempting to connect to GoPro wifi connection after 60s of display turning off fails

### ISSUE THREAD

**Issue by sleman** [gopro/OpenGoPro#192]
What is the bug in?
- BLE

**Describe the bug**
Attempting to connect to GoPro wifi connection after 60s of display turning off fails.

**To Reproduce**
- Connect to GoPro bluetooth camera.
- Wait 60 seconds
- Try to attempt to connect to wifi, connection will fail.
- Wait 5 seconds, try to connect again, connection will succeed.

Tried with stock firmware and latest firmware on GoPro Hero 10.

**Expected behavior**
Wifi connection should be established.

**Hardware**
- Camera: Hero 10 Black
- Windows 10

**Additional context**
Also tried to first send bluetooth commands for keep alive, toggling wifi AP, setting video mode. All failed to wake up camera so wifi connection is allowed.

**Comment by tcamise-gpsw** [comment]
Hi thanks for the clear report, I will try to replicate this.

Does the Wifi connection work for you if you attempt it as soon as possible after establishing the BLE connection?
