### ISSUE TITLE
Add Shutter Speed setting

### ISSUE THREAD

**Issue by sunwonlikeyou** [gopro/OpenGoPro#193]
As I searched, there are no options in Params.py for changing shutter speed. 
But there are chainging resolutions, FPS, .. .

**Comment by tcamise-gpsw** [comment]
Correct this setting does not exist and is not currently planned for implementation. I will leave this open as an enhancement request.

**Comment by hankzoid** [comment]
Ahh I just bought a Hero 12 thinking changing shutter speed and ISO limits via USB was a no brainer.

What other ways are there to match exposures on 20+ cameras? Showing a QR code to all of them with the labs firmware installed?

**Comment by tcamise-gpsw** [comment]
closing as duplicate since it is now tracked by top level protoune ticket: #561
