### ISSUE TITLE
GPU selection

### ISSUE THREAD

**Issue by GriffinRU** [gopro/OpenGoPro#200]
**Component**
What is the bug in?
- Demos (python sdk, etc)
- Tutorials
- Documentation
- Specs (BLE , HTTP)

**Describe the bug**
GoPro system tray application must have dropdown option to overwrite GPU selection or disable GPU assist. Problem -> GoPro application get confused upon new GPU driver install/uninstall (app restart fixes the problem, but doesn't report problem properly).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware**
- Camera: Hero9, etc.
- Desktop if applicable [e.g. Windows]
- Smartphone if applicable [e.g. iPhone6]

**Additional context**

**Comment by tcamise-gpsw** [comment]
Is this in relation to the GoPro webcam application?

If so, that is not related to this project (Open GoPro API) in any way and your best bet is to post on the [GoPro Forums](https://www.goproforums.com/)
