### ISSUE TITLE
Any chance to solve an issue that Webcam mode does not work properly on HERO10?

### ISSUE THREAD

**Issue by museatc** [gopro/OpenGoPro#206]
**Component**
- Specs (HTTP)

**Describe the bug**
[HTTP Specification v2.0](https://gopro.github.io/OpenGoPro/http_2_0)
Following this document, I connected the Raspberry Pi and HERO 10 and tried to use it as a webcam. I tried the command in the documentation and it didn't work as a webcam. I am creating a real-time object detection algorithm based on the video captured from a webcam.

**To Reproduce**
1. Connect HERO10 and Raspberry Pi with wired USB (using the included genuine USB A to C cable)
2. Disable USB control with "Disable wired usb control"
3. Start WebCam mode with "Start webcam"
The GoPro display says "WEBCAM", but it cannot be used as a webcam. The status code seems to be normal.

**Expected behavior**
I was hoping that I could capture the video as if I had a typical webcam (eg Logitech) connected to the Raspberry Pi.

**Screenshots**
![Screenshot1](https://user-images.githubusercontent.com/75404507/178408369-5bfa6a2b-bc18-47b2-ba45-1851138ae6d7.PNG)

**Hardware**
- Camera: HERO10 Black(v01.42.00)
- Desktop Raspberry Pi 4 8Gb(5.10.11-v7l+)

**Comment by tcamise-gpsw** [comment]
I don't think this is currently possible for you.

If you want to use the camera as a webcam with pre-existing tools, you need a suitable [driver](https://community.gopro.com/s/article/GoPro-Webcam?language=en_US). Unfortunately there is no such driver for Linux.

If you want to develop your own tool, you can follow the steps from the [spec](https://gopro.github.io/OpenGoPro/http_2_0#webcam)
