### ISSUE TITLE
Power off the camera via BLE/Http Api

### ISSUE THREAD

**Issue by pavlosharhan2** [gopro/OpenGoPro#211]
I want to power off the camera so It can cool down after long recording, and then wake It up again after some time.

I couldn't find any API command to power off the camera. Is that possible to do?

**Comment by pavlosharhan2** [comment]
I've found the solution here: https://github.com/KonradIT/goprowifihack

power off: BASE_URL+"/gp/gpControl/command/system/sleep"
wake up via wakeonlan: wakeonlan -i 10.5.5.9 -p 9 <gopro_mac_address>

**Comment by tcamise-gpsw** [comment]
You can also use the Sleep (0x05) [BLE Command](https://gopro.github.io/OpenGoPro/ble_2_0#live-streaming)
