### ISSUE TITLE
Can not Restart Preview Stream After Shutter Enable

### ISSUE THREAD

**Issue by tangjw** [gopro/OpenGoPro#228]
My device: GoPro Hero10 black.
if you not in recording, it's no bug , but when you call `/stream/start` then press the shutter button (i know can't preview in recording), the stream not restart after shutter button off . The  BLE api Status Code 32(Is Preview Stream enabled) always show `1: True`. And you call `/stream/stop` can not close the stream
```
start preview: /gopro/camera/stream/start
stop preview:  /gopro/camera/stream/stop
```
if you use this api, the stream restart after shutter button off, but the preview stream quality very bad
```
/gp/gpControl/execute?p1=gpStream&c1=restart
/gp/gpControl/execute?p1=gpStream&c1=stop
```

**Comment by tcamise-gpsw** [comment]
This is possible as found in #352, specifically in [this comment](https://github.com/gopro/OpenGoPro/issues/352#issuecomment-2004007570)
