### ISSUE TITLE
USB does not work with Hero 11 v01.10.00 firmware

### ISSUE THREAD

**Issue by garridozh** [gopro/OpenGoPro#230]
**Component**
- We have a bug related to wired connection on iOS devices.
- Specs HTTP

**Describe the bug**
We are using the HTTP Specification v2.0. It's working fine with GoPro Hero10, but it doesn't work on Hero11. With Hero11, the command to set a wired connection (/gopro/camera/control/wired_usb?p=1) returns a timeout.

The same steps are working properly with Hero10.

**To Reproduce**
1. I get the correct url socket
2. I send the request for wired connection with /gopro/camera/control/wired_usb?p=1
3. Timeout is received

**Expected behavior**
The expected behavior is to set a wired connection.

**Hardware**
- Camera: Hero11
- Devices: iPhone 6S, iPad Air 2, iPad Pro 2021, iPhone 13 Pro, and so on.

**Additional context**
I can see that Quik app still doesn't work on Hero11 with wired connection. It only works for Hero10 as well, like for us.

**Comment by tcamise-gpsw** [comment]
Hello. This is a known issue in the initial Hero 11 Firmware release. You can fix it by Resetting Connections, re-pairing, then trying again.

Note that this will be fixed in the next Firmware Update.

**Comment by StruffelProductions** [comment]
A new update 1.12 just dropped with "connectivity improvements". Does that include a fix for this issue?

**Comment by tcamise-gpsw** [comment]
This has been fixed as of:
- Hero 11 v01.20.00
- Hero 11 Mini v01.10.00
