### ISSUE TITLE
Hero 11 USB webcam mode not working

### ISSUE THREAD

**Issue by demiantres** [gopro/OpenGoPro#234]
With firmware 1.10:
- Connection to Windows machine with GoPro Webcam utility 1.2.1.813 -> does not work.
- Connection to macOS via USB -> does not work.

Hero 10 works fine.

**Comment by demiantres** [comment]
Resetting the network settings on the GoPro fixes the problem.

**Comment by tcamise-gpsw** [comment]
Hello, yes his is a known issue with the v 1.10 FW. I have pinned a duplicate ticket at #230
