### ISSUE TITLE
Allow camera to operate as RTSP server

### ISSUE THREAD

**Issue by mms-** [gopro/OpenGoPro#238]
While controlling functions is nice. This in the end is a camera. Grabbing live video or a live image should be a single http request. Not writing c++ code to read a UDP socket! Just run a RTSP server on camera like any IP camera does. Then any software can connect to the camera and it truly is 'open'. Too convoluted right now for simple scenarios.

**Comment by tranzmatt** [comment]
This would be a wonderful feature.  I'm trying to stream from my two Hero 10's on the same desktop box and it's a nightmare.

**Comment by tcamise-gpsw** [comment]
Should I keep this ticket open? Is there anything from the COHN solution that does not work for your use case?

**Comment by mms-** [comment]
Hi, this is good news, have not had a chance to try this but it should do it.

As long as the rtsp is stable, easy for us or the end user to provision, supports 4K along with different view modes it will work nicely.

**Comment by tranzmatt** [comment]
Just saw this.  I assume I need to upgrade firmware?

**Comment by tcamise-gpsw** [comment]
Yeah you'll need the latest firmware on Hero 12.

**Comment by gtirth** [comment]
I have got this latest Hero Pro 13 camera and I am trying to start the rtsp streaming on it but I am not getting anything?

Can someone plesae help?
