### ISSUE TITLE
What does LIVE_STREAM_ERROR_CAMERA_BLOCKED mean?

### ISSUE THREAD

**Issue by demiantres** [gopro/OpenGoPro#259]
My Hero 10 frequently returns the ``LIVE_STREAM_ERROR_CAMERA_BLOCKED`` error code when starting the live streaming mode. What does this error mean?

**Comment by tcamise-gpsw** [comment]
Hi any update here?

**Comment by demiantres** [comment]
Actually we cannot create this error anymore. It could be that we generated it before the latest firmware update.
