### ISSUE TITLE
Control GoPro Hero 10 from USB instead of WiFi/Bluetooth

### ISSUE THREAD

**Issue by Sladerix** [gopro/OpenGoPro#262]
Hi everyone one, I want to start studying this library but I wish to know if it's possible to control the GoPro though the USB port instead of using WiFi/Bluetooth

thanks in advance

**Comment by tcamise-gpsw** [comment]
Actually I made it pretty far on this today and expect to have something ready for release soon. I'll closed this so it is tracked in the duplicate linked ticket
