### ISSUE TITLE
Can't use two gopro as webcam simultaneously over USB in same device

### ISSUE THREAD

**Issue by mehrajagdish** [gopro/OpenGoPro#285]
**Component**
What is the bug in?
Can't use two go pro cameras as webcam simulatenously connected via USB on same device.

**Describe the bug**
When two go pro are connected to same device using USB we can access only one at a time as a webcam using USB.

**To Reproduce**
Connect two go pros and open any camera app to check webcam.

**Hardware**
- Camera: Hero11.
- Desktop : Windows 11.

**Comment by tcamise-gpsw** [comment]
Duplicate. This is tracked in #268
