### ISSUE TITLE
Continue support for Python 3.8

### ISSUE THREAD

**Issue by hhackbarth** [gopro/OpenGoPro#287]
**Is your feature request related to a problem or use case? Please describe.**
You announced that support for Python 3.8 will be dropped. In the installation dependencies already >=3.9 is checked.
Problem is that I have use cases, where I have to stick with Ubuntu 20.04 for some time and this only comes with 3.8.
I do not really see a reason for dropping 3.8 support.

**Describe the solution you'd like**
Keep on supporting Python 3.8.

**Describe alternatives you've considered**

**Additional context**

**Comment by tcamise-gpsw** [comment]
Hello. Perhaps I cut Python 3.8 a little early (it will be [marked ](https://devguide.python.org/versions/) end of life in October 2024) but it was preventing me from using newer Python features. 

Basically I want to keep this project modern and will be adding 3.11 support soon. So I do not plan on supporting 3.8.

My recommendation is to [install ](https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/)a newer version of Python.
