### ISSUE TITLE
Implement autonomous pairing on Linux

### ISSUE THREAD

**Issue by tcamise-gpsw** [gopro/OpenGoPro#29]
It is not currently possible, using Bleak, to autonomously pair. That is, the device must first be paired using BlueZ from the CLI.

**Comment by tcamise-gpsw** [comment]
There is currently an open PR in bleak for this: https://github.com/hbldh/bleak/pull/523

This is blocked until that is merged.

**Comment by tcamise-gpsw** [comment]
I missed this somehow. This is pretty clever! I'll try it out and if it works will open a PR to get this into the Python SDK

**Comment by tcamise-gpsw** [comment]
@pavlosharhan2 I finally got around to trying this today but I must be missing something because it is not working for me.

I tried debugging by calling `yes | bluetoothctl` from the command line. But this always just returns an error: "Invalid command in menu main: yes"

Any ideas?

**Comment by pavlosharhan2** [comment]
> @pavlosharhan2 I finally got around to trying this today but I must be missing something because it is not working for me.
> 
> 
> 
> I tried debugging by calling `yes | bluetoothctl` from the command line. But this always just returns an error: "Invalid command in menu main: yes"
> 
> 
> 
> Any ideas?

@tcamise-gpsw are you running python script with sudo?

**Comment by tcamise-gpsw** [comment]
Yes I am. 

Actually I ended up finding another way to do this with [pexpect](https://pexpect.readthedocs.io/en/stable/):

```
bluetoothctl = pexpect.spawn("bluetoothctl")
# bluetoothctl.logfile = sys.stdout.buffer
bluetoothctl.expect("Agent registered")
bluetoothctl.sendline(f"pair {handle.address}")
bluetoothctl.expect("Accept pairing")
bluetoothctl.sendline("yes")
bluetoothctl.expect("Pairing successful")
```

I like this and it seems to be working. I'll merge this soon.

**Comment by tcamise-gpsw** [comment]
Closing this since it is now functionally working. The cleaner solution is still to implement this through bleak. If bleak ever supports this, we will adopt it.
