### ISSUE TITLE
Add more details about go pro while using it as a webcam(UDP stream).

### ISSUE THREAD

**Issue by mehrajagdish** [gopro/OpenGoPro#295]
There is no official documentation which mentions the focal length and field of vision.
I need the below details for the gopro UDP stream for each mode(WIDE,NARROW,SUPERVIEW,LINEAR):

- focal length
- fov (horizontal)

**Comment by KonradIT** [comment]
That's super specific and generally not relevant to 99.99% of users. Webcam mode doesn't have EIS, so you can take normal FOV from older cameras as an indication.

https://gopro.com/help/articles/question_answer/hero7-field-of-view-fov-information?sf96748270=1

Stream is 16:9.
