### ISSUE TITLE
GoPro sends wrong UUID format

### ISSUE THREAD

**Issue by bichimarius** [gopro/OpenGoPro#308]
### Discussed in https://github.com/gopro/OpenGoPro/discussions/307

<div type='discussions-op-text'>

<sup>Originally posted by **bichimarius** February  1, 2023</sup>
Hi guys,

I have developed Windows Forms App (.NET Framework 4.8) with your API and I discovered an issue:

After first camera connection attempt everything works fine, from the 2nd attempt the device wakes up and sends different UUID which doesn't match the UUID pattern from documentation: e.g. **00002a19-0000-1000-8000-00805f9b34fb**
How can I reconnect device properly in order to get status updates from the 2nd connection attempt too, not just for the 1st one?

This happens when the device is waked up after manually power off or battery removal.

Thanks!</div>

**Comment by tcamise-gpsw** [comment]
Hi. Can you provide some more information or a set of steps to duplicate this. Are you referring to the UUID sent during advertising or a UUID used to access characteristics. Also, which status updates are you talking about?
