### ISSUE TITLE
Getting network error in livestream even if Go Pro is connected with Wifi connection

### ISSUE THREAD

**Issue by imsourajit** [gopro/OpenGoPro#324]
**Component**
What is the bug in?
 I am connected to my home wifi network and tried doing a live stream using Youtube live stream key and api.video stream key. After 3-4 mins I am getting a popup of Network Error in Go Pro

**Describe the bug**

**To Reproduce**
 Go through the below link and set up livestream urls. Scan QR code after setting up the required field. 
 Link - https://gopro.github.io/labs/control/rtmp/

**Expected behavior**
It should do streaming till I click on the shutter 

**Hardware**
- Hero 10 black

**Comment by tcamise-gpsw** [comment]
Is this actually related to Open GoPro? Are yo using Open GoPro API's or just trying to live stream from the Quik app?
