### ISSUE TITLE
Get Firmware version via API

### ISSUE THREAD

**Issue by tranzmatt** [gopro/OpenGoPro#328]
Is there way to get a camera's firmware version via the API?  I want to determine my camrea's capabilities by comparing its model and firmware against the capabilties.json file, but can't get the firmware version

**Comment by simohn** [comment]
I would also be interested in that feature! I didn't find anything in the docs..

**Comment by tcamise-gpsw** [comment]
Hello. Yes, this is possible via the Get Hardware Info command for [BLE ](https://gopro.github.io/OpenGoPro/ble_2_0#get-hardware-info) and [HTTP](https://gopro.github.io/OpenGoPro/http_2_0#commands-quick-reference) (`/gopro/camera/info`)
