### ISSUE TITLE
Continuation bit is incorrect in BLE Packetization Example in Spec

### ISSUE THREAD

**Issue by IvanKalaica** [gopro/OpenGoPro#336]
**Component**
- Specs (BLE)

**Describe the bug**
See the screenshot.

**To Reproduce**
1. Go to [Packet headers section](https://gopro.github.io/OpenGoPro/ble_2_0#packet-headers)

**Expected behavior**
Explained in the screenshot.

**Screenshots**
![Screenshot 2023-05-04 at 21 23 16](https://user-images.githubusercontent.com/71653/236311029-26beec24-6d11-4b61-b8a5-e4d01b277f96.png)

**Comment by tcamise-gpsw** [comment]
Documentation has been updated per [this commit](https://github.com/gopro/OpenGoPro/commit/3ba26fb360ab5cda691b8f05e5013db61a502af1)
