### ISSUE TITLE
Control playback of media on camera

### ISSUE THREAD

**Issue by rgov** [gopro/OpenGoPro#340]
Most of the functionality of the API revolves around capture or transfer of media. If I'm not mistaken, there's no way to command the GoPro itself to play a video file from its storage.

I have a use case where this would be useful, where the camera is controlled by an ESP32 which doesn't have its own display or speakers. Being able to start playback of a file on the camera would allow the controller to give feedback to the user.

**Comment by tcamise-gpsw** [comment]
Hello. Your understanding of the current OpenGoPro API is correct. I will close this since there are no plans to implement such UI control.
