### ISSUE TITLE
Wrong date in OTA firmware catalog for H11 Black Mini

### ISSUE THREAD

**Issue by KonradIT** [gopro/OpenGoPro#355]
**Component**
What is the bug in?: Firmware Catalog JSON response (https://api.gopro.com/firmware/v2/catalog)

**Describe the bug**

HERO11 Black Mini entry (item 9) contains `release_date` == `20220510` vs `20230510` (May 10, according to https://gopro.com/en/es/update/hero11-black-mini)

**Expected behavior**

```json
{
"release_date": "20230510"
}
```

**Hardware**
- Camera: Hero11 Black Mini

**Comment by tcamise-gpsw** [comment]
This has been updated now. The current date here is now:

```
{
"release_date": "20231214",
}
```
