### ISSUE TITLE
The Wifi driver parses CLI responses and only supports en_US where your language is de_DE

### ISSUE THREAD

**Issue by sponi78** [gopro/OpenGoPro#357]
Trying the demo "gopro-photo" i get the error message "The Wifi driver parses CLI responses and only supports en_US where your language is de_DE". Any chance to get the demos running on a windows 11 pc with a german os?

**Comment by tcamise-gpsw** [comment]
Unfortunately no this is not going to currently work with German OS. You can try the workaround as suggested [here](https://github.com/gopro/OpenGoPro/issues/320#issuecomment-1655795638)
