### ISSUE TITLE
USB Stream/Control Enhancement Request

### ISSUE THREAD

**Issue by leeprevost** [gopro/OpenGoPro#36]
enhancement request per discussion in issue 19

- _USB stream / control_: this has been confirmed to be coming in a future release. I don't have a date right now. If you want, you can make an enhancement request in this repo and I can update it when more information becomes available.

_Originally posted by @tcamise-gpsw in https://github.com/gopro/OpenGoPro/issues/19#issuecomment-897030867_

**Comment by KonradIT** [comment]
Well this is interesting 
![image](https://user-images.githubusercontent.com/5891284/133666696-700f3248-858d-4247-9840-3ec8b7172770.png)

**Comment by tcamise-gpsw** [comment]
Quick update...this should be coming in January.

**Comment by KonradIT** [comment]
That's great @tcamise-gpsw ! Will it be released for Kongs exclusively or Boilers too?

**Comment by tcamise-gpsw** [comment]
Hello all. The latest release contains wired / webcam [documentation](https://gopro.github.io/OpenGoPro/http_2_0#webcam) as well as a [demo ](https://gopro.github.io/OpenGoPro/demos/csharp/webcam)so I'll close this.
