### ISSUE TITLE
QuickCapture Api command

### ISSUE THREAD

**Issue by pavlosharhan2** [gopro/OpenGoPro#363]
Hi!

I'm interested in initiating quickcapture from my Raspberry Pi, like "The Remote" does it in the newest firmware versions for Hero10/11.
Is it possible to do? 

@tcamise-gpsw 
@KonradIT

**Comment by tcamise-gpsw** [comment]
Hi. You can implement this via the OpenGoPro API via:
1. Establish BLE connection
2. Send Set Shutter
3. Send the sleep command

There should be no noticeable timing difference between this behavior and the Remote's QuickCapture.
