### ISSUE TITLE
Python SDK install problem

### ISSUE THREAD

**Issue by dududunka** [gopro/OpenGoPro#367]
Hi! 

The bug is in Demos, python sdk (OpenGoPro\demos\python\sdk_wireless_camera_control\open_gopro\demos\video.py)

Сannot import name 'WirelessGoPro' from 'open_gopro', though open-gopro is downloaded 

1. Go to video.py
2. Click on Run
3. See error

I was expecting to capture and download the video

**Screenshots**
![image](https://github.com/gopro/OpenGoPro/assets/62661855/26fd1439-b865-418e-a180-f0068a81c250)

**Hardware**
- Camera: Hero7 black.
-  Windows 

I get this error with every functions, be it WirelessGoPro or WiredGoPro

Thanks

**Comment by tcamise-gpsw** [comment]
I just tested from Windows and see no problems. It's like a pycharm project configuration problem on your side.
You should be able to verify the following works (from a fresh virtual environment):
```
pip install open-gopro
gopro-photo
```
