### ISSUE TITLE
How to use GoPro wired connection 

### ISSUE THREAD

**Issue by GbekeAdesiyun** [gopro/OpenGoPro#381]
**Component**
What is the bug in?
Python Demo 

**Describe the bug**
Whenever I run the python demo script, photo.py to save a photo via the wired connection, I receive an Assertion Error. However, the same script works in the wireless case.

**To Reproduce**
1. Go to the photo.py script in the OpenGoPro repo
2. Connect the GoPro Hero 10 camera 
4. Run the photo.py script with the argument, "--wired" 

**Expected behavior**
The photo.py script runs properly and saves a photo. The photo then appears in the same directory as the photo.py file.

**Screenshots**
![image](https://github.com/gopro/OpenGoPro/assets/66129702/0ab55db9-0af4-404f-b501-279e8a4ec02b)

**Hardware**
- Camera: Hero10
- Desktop: Windows
- Python3.10.12

**Comment by tcamise-gpsw** [comment]
Thanks, I was not aware of this. I guess I'll make a note in the documentation that the GoPro driver needs to be installed first.
