### ISSUE TITLE
Cannot get wired connection Hero 10

### ISSUE THREAD

**Issue by AlexanderHackl** [gopro/OpenGoPro#383]
**Component**
What is the bug in?
USB/HTTP API

**Describe the bug**
HTTP Get does not work, gopro can not be pinged

**To Reproduce**
1. Connect Gopro to USB-C/Ethernet adaptor
2. connect Ethernet Cable to USB-C/Ethernet adaptor
3. Connect Ethernet Cable to PC
4. HTTP Get: http://172.2X.1YZ.51:8080/gopro/camera/control/wired_usb?p=1

**Expected behavior**
Camera can be controlled by HTTP commands

**Screenshots**
![IMG_1428](https://github.com/gopro/OpenGoPro/assets/17643966/51ba1a60-a78d-4841-80d6-cba6a4ab6637)

**Hardware**
- Hero 10, FW 10.5
- PC Win 10

**Additional context**
IP adress of gopro using last 3 digits of serial, tried automatic IP and manual using same range as gopro, tried to enable wired_usb via wifi before, tried usb directly, tried with power injection on adaptor and without. No lights flashing on ethernet socket on adaptor.

**Comment by KonradIT** [comment]
You need to use a USB A to USB C cable.
