### ISSUE TITLE
Wired Control HTTP/USB not working on Win10

### ISSUE THREAD

**Issue by AlexanderHackl** [gopro/OpenGoPro#384]
**Component**
What is the bug in?
HTTP/USB API
Windows 10 driver

**Describe the bug**
Connection with Windows 10 not possible, GoPro is shown as CDC NCM in other devices, no driver available

**To Reproduce**

- Connect GoPro to Windows10 computer via USB
- Try HTTP Get Command: http://172.2x.1yz.51:8080/gopro/camera/control/wired_usb?p=1
- Go to device manager/other devices/CDC NCM

**Expected behavior**
GoPro switches to wired control mode

**Screenshots**

**Hardware**
- Camera: Hero10, FW 01.50
- Windows 10

**Additional context**
Works on MacOS devices, does not work on WIN10, is there a NCM driver?

**Comment by KonradIT** [comment]
Install GoPro Webcam for windows.

https://community.gopro.com/s/article/GoPro-Webcam?language=en_US
