### ISSUE TITLE
Python SDK is using enum name instead of value for Set Setting Endpoint

### ISSUE THREAD

**Issue by tony-gutierrez** [gopro/OpenGoPro#400]
**Component**
What is the bug in?
- python sdk

**Describe the bug**
The sdk is resulting in http command like:
`http://172.28.151.51:8080/gopro/camera/setting?setting=162&option=MaxLensMode.DEFAULT`
instead of:
`http://172.28.151.51:8080/gopro/camera/setting?setting=162&option=0`

**To Reproduce**
1. Run the video demo with logging level set to DEBUG with cam connected to USB
2. Observe the URLs called

**Expected behavior**
Correct url

**Hardware**
- Camera: Hero11 black
- Desktop if applicable MAC

**Comment by tony-gutierrez** [comment]
Looks like this fixes the issue

![bug](https://github.com/gopro/OpenGoPro/assets/15345331/c3b1a5e1-fdfc-4f07-81c2-84580a5f2941)

**Comment by tony-gutierrez** [comment]
@tcamise-gpsw

**Comment by tcamise-gpsw** [comment]
Thanks, this really should not have slipped by. Let me add some unit testing for regression and open a PR

**Comment by tony-gutierrez** [comment]
It seems like with a bad value, the camera returns a 400, empty `{}`. With a good value but invalid, it returns a 403 with some JSON:
```
{
	"error": 2,
	"setting_id": 173
}
```

I discovered this as the Hero 11 does not seem to support this setting in the video.py demo (at least while on usb):
`await gopro.http_setting.video_performance_mode.set(Params.PerformanceMode.MAX_PERFORMANCE)`
`http://172.28.151.51:8080/gopro/camera/setting?setting=173&option=0`

**Comment by tcamise-gpsw** [comment]
Yeah the SDK does not make an effort to know which settings are supported on which cameras / FW.  That's why the demos don't assert on these commands.  They are only set for the relevant firmware versions where this setting mattered.

**Comment by tcamise-gpsw** [comment]
I just merged a PR to fix this. I will release 0.14.1 which will include this and other fixes now.
