### ISSUE TITLE
Is temperature information available in the Camera State via the SDK?

### ISSUE THREAD

**Issue by tony-gutierrez** [gopro/OpenGoPro#401]
**Is your feature request related to a problem or use case? Please describe.**
Use of the cameras (hero 11 blacks) in a commercial setting is resulting in overheating and shutdown

**Describe the solution you'd like**
I would like to monitor temp via the sdk and pause recording

**Comment by tcamise-gpsw** [comment]
There is at least this status right now:
![image](https://github.com/gopro/OpenGoPro/assets/76070353/d1074792-1fdc-4282-a4b2-17ac0a7d5773)
