### ISSUE TITLE
How to extend settings in the SDK

### ISSUE THREAD

**Issue by tony-gutierrez** [gopro/OpenGoPro#408]
Is there a way to extend the existing GoPro settings without modifying the SDK? I am new to python, so it might be obvious to others. 

**Describe the solution you'd like**
For example, the SDK is missing Beep control. I would like to extend it to add this setting, without modifying the  SDK source.
Something like:
```
class Beeps(GoProEnum):
            OFF = 0
            ON = 70
            
gopro.http_setting.beeps = HttpSetting[Beeps](communicatior??, SettingId.INTERNAL_87)
assert (await gopro.http_setting.beeps.set(Params.Beeps.ON)).ok
```

**Describe alternatives you've considered**
I am able to accomplish the need by modifying the SDK, but would prefer not to.

**Comment by tony-gutierrez** [comment]
@tcamise-gpsw  Any insight?

**Comment by tcamise-gpsw** [comment]
No this is not possible nor desired since the Python SDK is only intended to support the public facing OpenGoPro API.

**Comment by tony-gutierrez** [comment]
There is a lot of functionality in OpenGoPro that is not reflected in the Python SDK.
