### ISSUE TITLE
error install package

### ISSUE THREAD

**Issue by isdito** [gopro/OpenGoPro#432]
Hello when I install

`pip install open_gopro
`
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mysql-connector-python 8.2.0 requires protobuf<=4.21.12,>=4.21.1, but you have protobuf 3.20.3 which is incompatible.

**Comment by tcamise-gpsw** [comment]
I'm guessing you are installing globally and thus have dependency mismatches.
Can you try using a virtual environment?

**Comment by tcamise-gpsw** [comment]
So you're able to move past the install issue? if so I will close this.

If you are still seeing problems, please open a new ticket with more concise and detailed information than your last comment.
