### ISSUE TITLE
Does anybody know how to set rtmp url via ble?

### ISSUE THREAD

**Issue by ruzrulit** [gopro/OpenGoPro#434]
Hello everybody,

i am trying to set rtmp url for go pro camera via react native ble plx. Does anybody have a working example or an idea how to do that?
i can connect to the device but do not know hot to set rtmp.

**Comment by tcamise-gpsw** [comment]
Hello. There is documentation in the [livestream section](https://gopro.github.io/OpenGoPro/ble_2_0#live-streaming) of the BLE spec.

There is also a livestream demo in the [Python SDK](https://gopro.github.io/OpenGoPro/python_sdk/quickstart.html#livestream-demo)
