### ISSUE TITLE
Communication stops when using Bluez and Linux

### ISSUE THREAD

**Issue by adilerson** [gopro/OpenGoPro#435]
**Component**
What is the bug in?
- Specs (HTTP)

**Describe the bug**
list files and keep alive stop working

**To Reproduce**
1. Using Linux, I connect to the GoPro’s WiFi
2. I send a signal, start recording with http shutter start and end with stop, everything ok
3. I can list the files and download 2x, after this some functions stop working
4. So far I noticed that keep_alive and media/list stop working

**Expected behavior**
trying to make a quick connection via bluetoothctl:
[bluetooth]# connect CC:9C:B1:39:AA:DA
Attempting to connect to CC:9C:B1:39:AA:DA
[CHG] Device CC:9C:B1:39:AA:DA Connected: yes
Connection successful
[CHG] Device CC:9C:B1:39:AA:DA ServicesResolved: yes
[GoPro 9709]# pair CC:9C:B1:39:AA:DA
Attempting to pair with CC:9C:B1:39:AA:DA
Failed to pair: org.bluez.Error.ConnectionAttemptFailed

**Screenshots**

**Hardware**
- Camera: Hero12.
- Linux Ubuntu server

**Additional context**

if (isset($_GET['downloadLast'])) {
     $base = "http://10.5.5.9:8080";
     $list =
     $destinationdirectory = '/var/www/html/360Linux/360v2/celular/videos/tmp/';
     $currentevent = currentevent();
     $list = "$base/gopro/media/list";
     $url = $lista;
     **$json = file_get_contents($url);** // espta stops working
     $data = json_decode($json, true);
    
    requesting through php apache linux it shows:
http://10.5.5.9:8080/gopro/media/list displays the files 2 to 3 times, after copying files 2 times it stops accessing the file list. But the cell phone continues to access normally, not being a problem with the GoPro, but with the connection to Linux

**Comment by adilerson** [comment]
Linux Ubuntu server 22.04

**Comment by tcamise-gpsw** [comment]
Can you provide a log or complete script so that I can reproduce this?
