### ISSUE TITLE
docs: wrong "internal battery level" documentation

### ISSUE THREAD

**Issue by alestiago** [gopro/OpenGoPro#441]
GoPro Hero12 Black can report a battery level with a value "4" when on 100%.

This is not documented, since the [documentation](https://gopro.github.io/OpenGoPro/http_2_0#status-ids) specifies the battery level value range from 0 to 3.

**Comment by tcamise-gpsw** [comment]
4 == charging. I'll work on adding this to the docs.

**Comment by alestiago** [comment]
Thanks for the clarification!

**Comment by tcamise-gpsw** [comment]
Documentation has been updated from [this commit](https://github.com/gopro/OpenGoPro/commit/3ba26fb360ab5cda691b8f05e5013db61a502af1)
