### ISSUE TITLE
docs: wrong name or description on WLAN SSID

### ISSUE THREAD

**Issue by alestiago** [gopro/OpenGoPro#442]
_Status ID_ value 29 has name "WLAN SSID" but the description details it as "provisioned WIFI **AP** SSID".

On the other hand _Status ID_ value 30 has name "Ap ssid" but the description details it as "Camera’s WIFI SSID".

![Screenshot 2023-12-06 at 17 41 07](https://github.com/gopro/OpenGoPro/assets/44524995/db14bfe5-60c2-40f9-b21e-57bed84afa3a)

In GoPro Hero12 Black, _Status ID_ value 29 is empty whereas _Status ID_ value 30 is not.

---

Source: https://gopro.github.io/OpenGoPro/http_2_0#status-ids

**Comment by tcamise-gpsw** [comment]
Actually these are the correct descriptions. To summarize in a different way here:
29 == The SSID of the AP the camera is connected to
30 == The camera’s SSID while in AP Mode.

**Comment by tcamise-gpsw** [comment]
We ended up clarifying the status descriptions [here](https://github.com/gopro/OpenGoPro/commit/3ba26fb360ab5cda691b8f05e5013db61a502af1)
