### ISSUE TITLE
wifi_command_zoom.py: missing '/' before 'gopro/camera/...'

### ISSUE THREAD

**Issue by TadayukiOkada** [gopro/OpenGoPro#45]
https://github.com/gopro/OpenGoPro/blob/30e83c1da4514aaa04e29f769bf13d192028f420/demos/python/tutorial/tutorial_modules/tutorial_6_send_wifi_commands/wifi_command_zoom.py#L18

'/' is missing before 'gopro', so it errors out with: Failed to parse: http://10.5.5.9:8080gopro/camera/digital_zoom?percent=50

**Comment by tcamise-gpsw** [comment]
This is fixed as of the 2.0 tag (i.e. latest main).
