### ISSUE TITLE
Starting Webcam with 'res' or 'fov' query parameters fails

### ISSUE THREAD

**Issue by AlexSkillman10** [gopro/OpenGoPro#459]
**Component**
What is the bug in?
- Documentation
- Specs (BLE , HTTP)

**Describe the bug**
The res and fov parameters for the /gopro/webcam/start command don't seem to work. I think the documentation tables might be wrong.
 
![image](https://github.com/gopro/OpenGoPro/assets/125175965/ecb92c24-4d72-4737-b49f-5b4c61cf1c4a)

**To Reproduce**
Send /gopro/webcam/start command with res or fov parameters from documentation. Request fails.
![image](https://github.com/gopro/OpenGoPro/assets/125175965/737b0931-2fcb-44f6-9ddc-2f3d2dd08a86)

**Expected behavior**
Request starts webcam. Port and protocol work.
![image](https://github.com/gopro/OpenGoPro/assets/125175965/c3cc290c-9437-4584-ab68-3b313ef12357)

**Hardware**
- Camera: Hero11Black

**Comment by tcamise-gpsw** [comment]
Hi I think you have outdated docs. The correct [parameters](https://gopro.github.io/OpenGoPro/http#tag/Webcam/operation/OGP_WEBCAM_START) are: 

![image](https://github.com/gopro/OpenGoPro/assets/76070353/ca7a13ba-666d-41ed-90f9-a5273f406af6)
