### ISSUE TITLE
Webcam for HERO11 Black mini not working

### ISSUE THREAD

**Issue by JHSawatzki** [gopro/OpenGoPro#460]
**Component**
What is the bug in?
- Demos (python sdk)
- Documentation
- Specs (HTTP)

**Describe the bug**
Using Webcam with HERO11 Black mini with USB and HTTP is not working.

**To Reproduce**
1. Send http://172.2x.1xx.51:8080/gopro/camera/control/wired_usb?p=0
2. Send http://172.2x.1xx.51:8080/gopro/webcam/start?res=9&fov=3
4. See error:
{
    "status": 0,
    "error": 6,
    "supported_settings": [
        {
            "display_name": "Res",
            "supported_options": []
        }
    ]
}
5. Send http://172.2x.1xx.51:8080/gopro/webcam/start?fov=3
6. See error:
{
    "status": 0,
    "error": 6
}

**Expected behavior**
The webcam mode should properly start with the given parameters. The given python examples also fail.

**Hardware**
- Camera: Hero11 Black mini (Firmware GoPro Labs, v2.40.70, Decemeber 2023)
- Desktop Windows 10 x64, python 3.10

**Additional context**
none

**Comment by tcamise-gpsw** [comment]
Hello. Unfortunately there is not Webcam functionality on Hero 11 Black Mini. You can see these since the camera is not listed in any of the [Webcam API's](https://gopro.github.io/OpenGoPro/http#tag/Webcam)
