### ISSUE TITLE
GoPro 7 Black - media mod to connect bluetooth mic

### ISSUE THREAD

**Issue by Bach-Danielsson** [gopro/OpenGoPro#463]
Maybee an off topic request and sorry for that 

Is there any information available regarding  designing a media mod to connect by USB to Gopro 7 Black 
I thinking of designing a media mod that allow me to connect bluetooth mic to the camera.

- usb communication (audio in - mic )

**Comment by tcamise-gpsw** [comment]
Hi. Yeah this is mostly out of the scope of Open GoPro.
The best we can provide is the [HTTP via USB](https://gopro.github.io/OpenGoPro/http#section/Setup) documentation but you're not going to be able to transfer audio via that interface.
