### ISSUE TITLE
Bluetooth connection on Raspberry Pi and Bookworm

### ISSUE THREAD

**Issue by demiantres** [gopro/OpenGoPro#464]
I am having a hard time connecting GoPro cameras (different models, including Hero 9, 10, 11, and 12) to a Raspberry Pi 4 and 5 running Bookworm via Bluetooth. The cameras are not detected (listed) most of the time (e.g. using "bluetoothctl" -> "scan on") and when they are detected then the connection fails almost every time. I think it has something to do with Bookworm because with Bulls Eye it worked.

Is anyone experiencing similar problems and has eventually a fix or workaround?

**Comment by tcamise-gpsw** [comment]
Hello. Can you post a log or some type of more information? I've never had issues manually using `bluetoothctl`
