### ISSUE TITLE
Use proper HTTP method types

### ISSUE THREAD

**Issue by axeljaeger** [gopro/OpenGoPro#470]
**Component**
- Specs (HTTP)

**Describe the bug**
Currently, the GoPro HTTP API only uses HTTP GET and POST Requests. According to https://www.w3schools.com/tags/ref_httpmethods.asp
"GET requests are only used to request data (not modify)"

Currently, whether a method is using GET or POST seems a bit random and DELETE is not used at all.

**Expected behavior**
- Methods that modify data on the camera must not use GET, but POST, PUT or DELETE.
- For deleting data on the camera, e.g. 
  - https://gopro.github.io/OpenGoPro/http#tag/COHN/operation/GPCAMERA_CLEAR_HOME_NETWORK_CERT
  - https://gopro.github.io/OpenGoPro/http#tag/Hilights/operation/OGP_REMOVE_HILIGHT
 Use DELETE method.

PS: I am so glad that you guys now use a proper API description. I was about to create my own: 
- https://github.com/axeljaeger/gopro-openapi
but will archive it and redirect to your page.

**Comment by tcamise-gpsw** [comment]
Yes this would be nice and something I have been pushing for for new commands. But there is definitely not going to be a major rewrite of the API any time soon.
