### ISSUE TITLE
Hero 12 Will not work with Gopro Remote in Multicam

### ISSUE THREAD

**Issue by GeeForce01** [gopro/OpenGoPro#471]
Gopro Hero 12/Gopro Smart Remote

**Describe the bug**
The Gopro Remote looses "bind" with the Gopro Smart remote when switched off using the remote in multicam setting on the remote. It connects once, until you use the lower left button to power off the camera's, once you use the same button to switch the cameras on, they go on, but do not connect to the remote

**To Reproduce**
Connect/pair Hero 12's to the Smart Remote as per instructions (simple)
Select Multicam under the "Connect to" (your camera's including the hero 12's will be here)
Press record, on and off
Use lower left button to turn off camera's to save battery
Use the same process to switch them on (works with my Hero 9,11 and Max), except when I have the Hero 12 as part of the Multicam
Camera's turn on, remote gets stuck on "searching"

**Expected behavior**
It would be great if the camera/remote could work with Multicam - Gopro has been avoiding all of these requests, even on their support pages.

**Hardware**
- Camera: Hero 12 x 2 units, Gopro Smart Remote

**Additional context**
A simple google search will return many results of this setup not working

**Comment by tcamise-gpsw** [comment]
Hello, I can't speak to what is happening on the support pages but unfortunately this ticket doesn't actually relate to the Open GoPro API since:
- Open GoPro [does not support](https://gopro.github.io/OpenGoPro/#compatibility) the remote. 
- The interface between the remote and camera is not Open GoPro.
