### ISSUE TITLE
Start/Stop Recording via USB

### ISSUE THREAD

**Issue by jimmek** [gopro/OpenGoPro#472]
My application is simple in concept. Via USB connection, Start and Stop recording. No other functionality required. Did not see any Tutorial, Demo or FAQ for USB useage . I am programming in C using National Instruments LabWindows/CVI. How do you suggest I proceed? Is there already an executable for sending commands via USB such as in a command line or other means?  Thank you.

**Comment by tcamise-gpsw** [comment]
The only demo that shows such behavior is the Wired Webcam Demo in the [Python SDK](https://gopro.github.io/OpenGoPro/python_sdk/quickstart.html#wired-webcam-demo)

I'm assuming you have already read the relevant parts of the HTTP spec:
- [setup](https://gopro.github.io/OpenGoPro/http#section/Setup)
- [webcam](https://gopro.github.io/OpenGoPro/http#tag/Webcam)
