### ISSUE TITLE
400 BAD REQUEST whenever setting is set (HTTP over USB)

### ISSUE THREAD

**Issue by walrashoud** [gopro/OpenGoPro#486]
**Component**
What is the bug in?
HTTP (USB)

**Describe the bug**
Whenever I try to set a setting, I get 400 BAD REQUEST. E.g. http://IP:8080/gopro/camera/setting/59/0 is supposed to change poweroff to never, but I get bad request. 

**To Reproduce**
Connect the camera over USB
Send this request: http://IP:8080/gopro/camera/setting/59/0

**Expected behavior**
200 OK, with the setting set 

**Hardware**
- Camera: Hero11, Black.
- Mac OS

**Comment by tcamise-gpsw** [comment]
Hey sorry this was a bug in the spec. It is updated now with the correct [endpoints](https://gopro.github.io/OpenGoPro/http#tag/settings) which would be, i.e.:

```
http://10.5.5.9:8080/gopro/camera/setting?setting=59&option=12
```
