### ISSUE TITLE
http Setup  Same IP address

### ISSUE THREAD

**Issue by yuey286** [gopro/OpenGoPro#489]
<img width="473" alt="g_20240219235832" src="https://github.com/gopro/OpenGoPro/assets/12585826/c1ca235d-db69-4121-941b-d50706529ccc">

**Component**
I bought 12 GoPro12s for shooting. According to the official API, I clumsily wrote a py script to download videos through http. However, the last three digits of the serial numbers of the two cameras are the same. Is there any way to download video materials at the same time? ?
https://gopro.github.io/OpenGoPro/http#section/Setup

**Comment by bfreeland-gpsw** [comment]
Unfortunately we do not support multiple cameras connected to the same device over USB. If you want to control multiple cameras from the same device I recommend using [wi-fi station mode (aka Camera On the Home Network or COHN)](https://gopro.github.io/OpenGoPro/http#tag/COHN). As long as your wi-fi network has a DHCP server they should both receive unique addresses.
