### ISSUE TITLE
GoPro The Remote can conrol other devices?

### ISSUE THREAD

**Issue by nenkovarna** [gopro/OpenGoPro#492]
How I can connect other BLE device to GoPro Remote, to start together with camera?

I have read documentation of OpenGoPro but there is no answering for that.

I was trying to emulate the camera services and characteristics, but the remote control doesnt connect to the my device. 

Any idea from anyone?

**Comment by tcamise-gpsw** [comment]
Hello. Unfortunately the GoPro Remote[ is not supported](https://gopro.github.io/OpenGoPro/#compatibility) by Open GoPro and in any case does not use the Open GoPro interface.
