### ISSUE TITLE
Wrong Action ID in documentation

### ISSUE THREAD

**Issue by hugorezende** [gopro/OpenGoPro#494]
**Component**
What is the bug in?
- Documentation ([here](https://gopro.github.io/OpenGoPro/ble/protocol/id_tables.html#protobuf-ids))

**Describe the bug**
The Action ID of the `RequestGetApEntries` is wrong in the documentation. It's saying 0x04 when the correct is 0x03 (it's actually duplicated)

**Hardware**
- Camera: Hero9 BLACK

**Additional context**

**Comment by tcamise-gpsw** [comment]
This is [fixed now](https://gopro.github.io/OpenGoPro/ble/features/access_points.html#get-ap-scan-results).
There were a few others but I think I caught them all.
