### ISSUE TITLE
Preview while sending BLE commands

### ISSUE THREAD

**Issue by aveary** [gopro/OpenGoPro#496]
Is there a possible way to have a preview streaming to my laptop while I'm sending several shutter on/off commands, without interrupting the preview? I'm using two gopro hero 12 blacks in stereo to film objects for a research study. So far I'm only able to get single-webcam working by enabling the wifi AP on one camera, then manually selecting it windows wi-fi list, then running single-webcam. But while it's in this "WEBCAM" mode I'm not able to keep the BLE connection live to set shutter on/off. I only need one camera to stream.

**Comment by tcamise-gpsw** [comment]
I might not be understanding your top-level requirements here. Are you just trying to use multiple webcams simultaneously from the same computer? If so, there is a [Python demo](https://github.com/gopro/OpenGoPro/tree/main/demos/python/multi_webcam) to do exactly that.

Anyway: no, you can not use BLE when the GoPro is connected as wired webcam.
