### ISSUE TITLE
Capturing/Reviewing streamed video simultaneously

### ISSUE THREAD

**Issue by intiharj** [gopro/OpenGoPro#499]
I don't have a camera yet, and I'm looking for a solution that will fit this scenario. I'm a pole vault coach, and I'd like to have a camera mounted on a tripod that is streaming live video to a tablet over wifi. I want to walk around with the tablet, hand it to others, etc. I'd like to build an app on the tablet that would show the live video stream by default. It would also let me pause, rewind a bit and view an athlete's past jump in slow-mo multiple times. But while I'm reviewing the recent past, the app would continue to capture the video streaming from the camera. That way, no matter what I'm doing with the tablet, the app is capturing the entire practice. Would the OpenGoPro platform support this scenario?  Thank you,

**Comment by tcamise-gpsw** [comment]
Hello. Yes is possible. From the Open GoPro side all this really entails is configuring and starting a [Preview Stream](https://gopro.github.io/OpenGoPro/http#tag/Preview-Stream). You would then need to build your app to do with this stream as you wish.
