### ISSUE TITLE
i would like to turn on red LED light on gopro MAX

### ISSUE THREAD

**Issue by Fougl** [gopro/OpenGoPro#500]
Hi @tcamise-gpsw  ,

I would really appreciate some help. Most probably the led light can be turned on or start blinking with bluetooth, but I dont see any info on it except publish by konrad here https://github.com/KonradIT/goprowifihack/blob/master/Bluetooth/bluetooth-api.md
image

i need a way to show the employees that the camera is busy downloading or is about to download a video so that they wait and use other cameras which are available. Is there any other way to do this

**Comment by tcamise-gpsw** [comment]
Hello. Unfortunately this is not possible with the current Open GoPro API because:
1. MAX is not a [supported camera](https://gopro.github.io/OpenGoPro/#compatibility)
2. The LED setting is not exposed
