### ISSUE TITLE
HTTP API => Internal Server Error

### ISSUE THREAD

**Issue by Ektacom** [gopro/OpenGoPro#504]
When controlling the USB camera through the HTTP API through USB, sometimes the answer to a HTTP request is "Internal Server Error" with a HTTP status code equal to 500. 
When this response appears, then the gopro HTTP server is blocked: none request can be done to the gopro and there is no way to recover. The only solution is to unplug the camera.
I've experienced this problem on Gopro Black 12 (I don't know if the problem exit on other gopro cameras). Unfortunately I'm not able to reproduce the problem but from my experience, it can appear randomly on any request or request sequence.
- What could be the reason of this message ? Is there a way to mitigate this problem ?
- Is there a way to recover when it appears whithout having to restart the gopro camera ?

**Comment by pavlosharhan2** [comment]
I have a hope that this is fixed in today's 2.20 firmware!

**Comment by pavlosharhan2** [comment]
@Ektacom 

Hey, having the same issue, going to try today's new 2.20 firmware. Will see how it goes.

By the way, are you sure that unplugging the camera helps with this? All the people known to me having this problem say that only resetting the camera helps ( sometimes )

**Comment by Ektacom** [comment]
@pavlosharhan2 
I don't have any battery in the camera. The camera is powered throuyh USB : this may explain why when I unplug USB cable it "solves" my problem.

**Comment by pavlosharhan2** [comment]
UPD:
Haven't noticed this bug in the latest 2.20 Labs firmware

**Comment by tcamise-gpsw** [comment]
I'm unable to reproduce this with the latest firmware. Is anyone still having this issue?

**Comment by aoyurs** [comment]
I encountered the same issue with firmware version v2.20.70.
