### ISSUE TITLE
How to swich to Video mode via ble

### ISSUE THREAD

**Issue by pavlosharhan2** [gopro/OpenGoPro#514]
When recording videos, sometimes user occasionally presses the side button on the camera and it switches the mode to Photo or Timelapse.

I've been using /gp/gpControl/settings/144/12 command for a long time, but now I've focused my software on bluetooth API.
Is there any alternative to this legacy wifi command in Bluetooth API?  

Tried to send this: 0x03U, 0x90U, 0x01U, 0x0CU to 0074(Settings) characteristic, but It doesn't work. 

From the doc , I see only the ways to load specific presets, but I need It to do the same thing like when we press the side button

Thank you in ad

**Comment by tcamise-gpsw** [comment]
Hello. The closest way to approximate the mode button functionality in the Open GoPro API is with the "Load Preset Group" API. This is available via [HTTP](https://gopro.github.io/OpenGoPro/http#tag/Presets/operation/OGP_PRESET_SET_GROUP) and [BLE](https://gopro.github.io/OpenGoPro/ble/features/presets.html#load-preset-group).

**Comment by pavlosharhan2** [comment]
Thank you for quck response, I've tried this command below, but It's not working.  Does it look correct?
Can I use just group Id=0 for video mode, or do i need to query the available group ids via protobuf?
I hope there is a way to do that without implementing protobuf parsing in kotlin...



val setSettingCmd = ubyteArrayOf(0x06U, // total number of bytes in the query
            0x3EU, // command id ( load preset)
            0x04U, // preset id value size (4 bytes)
            0x00U, 0x00U, 0x00U, 0x00U)  // 0 as uint32
            
            
            
            <img width="644" alt="Screenshot 2024-04-11 at 2 30 14 PM" src="https://github.com/gopro/OpenGoPro/assets/9537
<img width="741" alt="Screenshot 2024-04-11 at 2 31 12 PM" src="https://github.com/gopro/OpenGoPro/assets/95373134/9bee58fe-eefa-4969-a255-81343f95cd08">
3134/ce689251-48f6-4d9d-9466-d024cb018846">

**Comment by pavlosharhan2** [comment]
Oh, I'm looking at group icon while i have to look at a group

**Comment by pavlosharhan2** [comment]
Thank you !
this one worked

val setSettingCmd = ubyteArrayOf(0x04U, // total number of bytes in the query
            0x3EU, // command id ( load preset)
            0x02U, // preset id value size (4 bytes)
            0x03U, 0xE8U)  // 1000 as uint32
            
            sent to 0074 characteristic
