### ISSUE TITLE
Method to connecting multiple GoPro devices to a single PC and getting each videos

### ISSUE THREAD

**Issue by onigiri5884** [gopro/OpenGoPro#520]
Please tell me how to connect multiple GoPro devices to a single PC and access each videos. 
I think it would be possible if each GoPro devices transfer each different UDP addresses, but I don't know how to do.

**Comment by Fougl** [comment]
Hi, the keyword is COHN. Below are the posts related to your question
https://github.com/gopro/OpenGoPro/issues?q=cohn

**Comment by tcamise-gpsw** [comment]
Also see:
- COHN [tutorials](https://gopro.github.io/OpenGoPro/tutorials/cohn)
- [BLE](https://gopro.github.io/OpenGoPro/ble/features/cohn.html#) / [HTTP](https://gopro.github.io/OpenGoPro/ble/features/cohn.html#) provisioning documentation
