### ISSUE TITLE
Set Night shutter via OpenGoPro ?

### ISSUE THREAD

**Issue by grelle** [gopro/OpenGoPro#524]
Is it possible to set the "Night shutter" or basically adjust the shutterspeed for night photography using OpenGoPro ? Seems that it is possible with GoProLabs firmware but I'm not really sure if all the GoProLabs settings is possible to utilise from OpenGoPro.
As far as I can understand, the GoProLabs functions need to be set with QR code, I was looking for a solution to set it programmatically via USB/Wifi/Bluetooth

**Comment by tcamise-gpsw** [comment]
Hello. You can find all of the settings that are configurable through Open GoPro [here](https://gopro.github.io/OpenGoPro/ble/features/settings.html#setting-ids). 

Shutter speed is currently not one of them. There is [already a ticket](https://github.com/gopro/OpenGoPro/issues/193) to track adding it so I will close this as duplicate
