### ISSUE TITLE
Add photo resolution and timelapse interval settings

### ISSUE THREAD

**Issue by sam-dumont** [gopro/OpenGoPro#533]
As issue 416 has been closed already I'm reopening a new one. 

              > So to my understand this is all currently documented. Is there something I'm missing?

I don't think every setting is documented. I'm currently writing a Garmin Edge remote control and when I parse the NotifyPresetStatus reply, there are settings which are missing from the documentation.

For instance, here is what I receive for the photo group ID
```
         preset_group_array {
           id: PRESET_GROUP_ID_PHOTO
           preset_array {
             id: 65536
             mode: FLAT_MODE_PHOTO
             title_id: PRESET_TITLE_PHOTO
             user_defined: false
             icon: PRESET_ICON_PHOTO
             setting_array {
               id: 122
               value: 101
               is_caption: true
             }
             is_modified: true
           }
           preset_array {
             id: 65537
             mode: FLAT_MODE_LIVE_BURST
             title_id: PRESET_TITLE_LIVE_BURST
             user_defined: false
             icon: PRESET_ICON_LIVE_BURST
             setting_array {
               id: 133
               value: 0
               is_caption: true
             }
             setting_array {
               id: 121
               value: 0
               is_caption: true
             }
             is_modified: false
           }
           preset_array {
             id: 65538
             mode: FLAT_MODE_PHOTO_BURST
             title_id: PRESET_TITLE_BURST
             user_defined: false
             icon: PRESET_ICON_BURST
             setting_array {
               id: 147
               value: 4
               is_caption: true
             }
             setting_array {
               id: 123
               value: 101
               is_caption: true
             }
             is_modified: true
           }
           preset_array {
             id: 65539
             mode: FLAT_MODE_PHOTO_NIGHT
             title_id: PRESET_TITLE_NIGHT
             user_defined: false
             icon: PRESET_ICON_PHOTO_NIGHT
             setting_array {
               id: 19
               value: 0
               is_caption: true
             }
             setting_array {
               id: 122
               value: 101
               is_caption: true
             }
             is_modified: false
           }
           can_add_preset: true
         }
```

Settings with IDs 133, 147 and 19 are not documented.

_Originally posted by @sam-dumont in https://github.com/gopro/OpenGoPro/issues/416#issuecomment-2075088891_

**Comment by tcamise-gpsw** [comment]
Yes that is correct: not all settings are documented / exposed through Open GoPro.

Some are deprecated, internal, or otherwise do not have reason to be exposed.

**Comment by sam-dumont** [comment]
@tcamise-gpsw Thanks for the reply. Some settings are still missing I think. For instance, I can't find a way to get the interval of a TimeLapse on a GoPro Hero 9. Or an indication of the Photo resolution. It's not a huge issue but it would be nice to show the same settings as what's displayed on the GoPro

**Comment by tcamise-gpsw** [comment]
I'm working on a cleanup of the settings right now and will take a look at this after the update is pushed

**Comment by tcamise-gpsw** [comment]
Well I've finished the setting cleanup such each setting and each option within a setting is unique. 

But this has not solved the issue here. I'll leave this open as an enhancement request to add the requested settings:
- photo resolution
- timelapse interval

There are many internal settings that are not being publicly exposed for no valid reason. We need to go through and add these.

**Comment by sfoley-gpqa** [comment]
@sam-dumont 

That is a really cool app idea. Do you have any plans on developing a version with support for Garmin Fenix 6? I'm wearing one now and would really like that!

**Comment by sam-dumont** [comment]
> @sam-dumont 
> 
> 
> 
> That is a really cool app idea. Do you have any plans on developing a version with support for Garmin Fenix 6? I'm wearing one now and would really like that!

Unfortunately the interactions possible when using a watch are very limited. The only way to make it work would be to tie the recording to start/stop activity and lap button. Not ideal but could be doable. Also, Fenix 6 will never be supported because those devices lack the proper APIs (they can't deal with secure BLE). 

I'm already very slow to add features for Edge devices, and GoPro 12 are very tough to handle because they behave differently in terms of BLE advertising and pairing so I have a lot to finish first. Watch support is not going to be done very soon... Sorry!

**Comment by sfoley-gpqa** [comment]
> > @sam-dumont
> > That is a really cool app idea. Do you have any plans on developing a version with support for Garmin Fenix 6? I'm wearing one now and would really like that!
> 
> Unfortunately the interactions possible when using a watch are very limited. The only way to make it work would be to tie the recording to start/stop activity and lap button. Not ideal but could be doable. Also, Fenix 6 will never be supported because those devices lack the proper APIs (they can't deal with secure BLE).
> 
> I'm already very slow to add features for Edge devices, and GoPro 12 are very tough to handle because they behave differently in terms of BLE advertising and pairing so I have a lot to finish first. Watch support is not going to be done very soon... Sorry!

That's alright. The Edge project is still very cool!

**Comment by tcamise-gpsw** [comment]
Closing this since it has been implemented via:

The following settings have been documented:
- [Video Timelapse Rate](https://gopro.github.io/OpenGoPro/ble/features/settings.html#video-timelapse-rate-5)
- [Photo Timelapse Rate](https://gopro.github.io/OpenGoPro/ble/features/settings.html#photo-timelapse-rate-30)
- [Nightlapse Rate](https://gopro.github.io/OpenGoPro/ble/features/settings.html#nightlapse-rate-32)

There is no photo resolution setting as it is not configurable.
