### ISSUE TITLE
Wrong argument name for Delete Single Media File

### ISSUE THREAD

**Issue by romain-riviere** [gopro/OpenGoPro#535]
**Component**
What is the bug in?
- **Documentation**

**Describe the bug**
I am requesting to Firmware H22.01.02.30.70 from a Flutter Application on Android 12

Here in the doc : https://gopro.github.io/OpenGoPro/http#tag/Media/operation/OGP_DELETE_SINGLE_FILE
Documentation specifies that we should use parameter "p" to specify the file to delete but the gopro response is HTTP 400.
I've tried with the parameter "path" and the gopro response is HTTP 200 and it actually deletes the file.

**Screenshots**
Responses in my logs :

Error:
![image](https://github.com/gopro/OpenGoPro/assets/12347313/3ef52ea5-16cc-414e-9850-5a08cfaa4fd5)

Success:
![image](https://github.com/gopro/OpenGoPro/assets/12347313/c73ad56b-029e-413c-9746-3391963bbc36)

**Hardware**
- Camera: Hero11
- Desktop: MacOS Sonoma
- Smartphone: Samsung S10

**Comment by tcamise-gpsw** [comment]
Good catch. Let me verify and then I'll update the docs

**Comment by tcamise-gpsw** [comment]
This has been fixed.
