### ISSUE TITLE
Pair cameras with RPI without the GoPro app

### ISSUE THREAD

**Issue by Fougl** [gopro/OpenGoPro#539]
I am already thinkng about the future, so the feature request would go to future cameras.

I have various locations with multiple cameras, that are changing - locations are added or closed, cameras are added or relocated or malcunctioned, RPIs are changed due to malfunction etc. I have RPIs on site or over VPN server which need to control the GoPro max. Now I have to go to every location and pair the cameras on site with the RPIs. I know if GoPro max 2 will have COHN, this problem will go away for me, cause I will have same network SSID and password setup on all locations, and then will get connected immediately. So probably this feature is not important for me, but it might be. And for others as well.

**Comment by tcamise-gpsw** [comment]
Hello I'm trying to distill this down to an actionable ticket but I'm not exactly sure what you're requesting here. Is it that Max 2 has COHN functionality?
