### ISSUE TITLE
Unable to Use GoPro Wireless Python SDK, Assertion Errror

### ISSUE THREAD

**Issue by Ahmad-197** [gopro/OpenGoPro#545]
Hi, 
I am trying capture a photo by using the demo wireless python sdk. However, I am facing some errors. 

Steps to reproduce:
Run `gopro-photo` in the terminal.

![image](https://github.com/gopro/OpenGoPro/assets/86935871/43c326e1-762b-4fff-9be1-09aeaebaebde)

What can I do to solve the issue?

P.S. I am using Python 3.10.7  and open-gopro-0.16.1. Camera: Hero 11 mini Black. I have also tried using open-gopro 0.13.1 and 0.11.2. I get the following error while using open-gopro 0.11.2.

![image](https://github.com/gopro/OpenGoPro/assets/86935871/1234ff3a-4ea3-461b-a753-3200690abced)

_Originally posted by @Ahmad-197 in https://github.com/gopro/OpenGoPro/issues/417#issuecomment-2104436282_

**Comment by tcamise-gpsw** [comment]
Hello. Hero 11 Black Mini does not have the capability to take photos: it can only take videos.
