### ISSUE TITLE
Router connection camera issue

### ISSUE THREAD

**Issue by Seven0145** [gopro/OpenGoPro#546]
I would like to use a computer to send Python photo commands and have the camera return photos. Can you give me an example

**Comment by tcamise-gpsw** [comment]
There is a [Python SDK](https://gopro.github.io/OpenGoPro/python_sdk/) which includes, among many other things, a [photo demo ](https://gopro.github.io/OpenGoPro/python_sdk/quickstart.html#photo-demo) to do exactly that.
