### ISSUE TITLE
running gopro-photo

### ISSUE THREAD

**Issue by maccardo** [gopro/OpenGoPro#548]
I just installed the latest open-gopro from pipy (v0.16.1)
I also installed the gui demos.
I went to run the example gopro-photo and it returned an error.
I ran it as follows, with error.
D:\OpenGoPro>gopro-photo
INFO     13:10:10.391 Scanning for GoPro [A-Z0-9]{4} bluetooth devices...                                                                                              bleak_wrapper.py:120
INFO     13:10:14.879    Discovered: F4:76:4C:EB:72:D3: GoPro 7501                                                                                                     bleak_wrapper.py:133
INFO     13:10:14.884 Found 1 matching devices.                                                                                                                        bleak_wrapper.py:146
INFO     13:10:14.886 Establishing the BLE connection                                                                                                                         client.py:106
INFO     13:10:14.888 Establishing BLE connection to F4:76:4C:EB:72:D3: GoPro 7501...                                                                                  bleak_wrapper.py:213
INFO     13:10:17.230 Discovering characteristics...                                                                                                                   bleak_wrapper.py:358
ERROR    13:10:17.657 Error while opening: Could not read Descriptor value for 0032: Protocol Error 0x05: Insufficient Authentication                                 gopro_wireless.py:316
INFO     13:10:17.744 Terminating the BLE connection                                                                                                                          client.py:130
INFO     13:10:17.746 Disconnecting...                                                                                                                                 bleak_wrapper.py:413
INFO     13:10:20.962 Device disconnected!                                                                                                                             bleak_wrapper.py:416
ERROR    13:10:20.964 BleakError('Could not read Descriptor value for 0032: Protocol Error 0x05: Insufficient Authentication')                                                  photo.py:51
D:\OpenGoPro>

Why am I getting insufficient authentication.

Marco

**Comment by tcamise-gpsw** [comment]
The Bleak Python interface is not very robust so depending on when / if you reset either device you can run into these types of issues. If you start with a fresh connection state as described below, everything should work:

Reset the camera by choosing Connections –> Reset Connections
Use your OS’s bluetooth settings GUI to remove / unpair the GoPro
