### ISSUE TITLE
State status key 111 reports slow SD card for fast SD card (Hero 12 Black)

### ISSUE THREAD

**Issue by tony-gutierrez** [gopro/OpenGoPro#550]
**Component**
What is the bug in?
- Specs (BLE, HTTP)

**Describe the bug**
I am using a Hero 12 Black with the latest GP labs fw.  The camera state is reporting a slow SD card. This is the card I am using:

![331600914-b227edf7-9650-4834-a2f6-08a0bf38f24a](https://github.com/gopro/OpenGoPro/assets/15345331/eb63d2a9-6f81-4c04-a4de-8a7f1b633778)

**To Reproduce**
Install this card, and fetch camera state. Look at status[111]. 0 means card is too slow, according to doc wording.

**Expected behavior**
Is this card not suitable? Why is 111 reporting 0? Is the documentation for 111 wrong here? 
https://gopro.github.io/OpenGoPro/http#tag/Query/operation/OGP_GET_STATE
![image](https://github.com/gopro/OpenGoPro/assets/15345331/15f289c6-86b8-487a-90d3-4c92af8177f5)

**Comment by bfreeland-gpsw** [comment]
Hi @tony-gutierrez,

Status 111 is intended as a error flag to indicate a problem with the SD card's write speed. A value of 1 indicates the SD card write speed is too slow while a value of 0 indicates the write speed is acceptable. We will update the documentation in future to clarify this.

**Comment by tcamise-gpsw** [comment]
I'll update the status description to "Is there a minimum SD Card write speed error?"

**Comment by tcamise-gpsw** [comment]
This has been updated for [BLE ](https://gopro.github.io/OpenGoPro/ble/features/statuses.html#sd-card-write-speed-error-111) and [HTTP](https://gopro.github.io/OpenGoPro/http#schema/State)
