### ISSUE TITLE
unable to execute tutorial_1_connect_ble.py

### ISSUE THREAD

**Issue by maccardo** [gopro/OpenGoPro#552]
Using a Hero 10 python 3.11 and latest checkout of tutorials on windows. Seems to find it but then burps on authentication.
How to I resolve this?

D:\OpenGoPro\demos\python\tutorial\tutorial_modules\tutorial_1_connect_ble>python ble_connect.py
INFO     13:50:19.506 Scanning for bluetooth devices...                                                                                                       ble_connect.py:55
INFO     13:50:24.596 Found 0 matching devices.                                                                                                               ble_connect.py:77
INFO     13:50:29.604 Found 0 matching devices.                                                                                                               ble_connect.py:77
INFO     13:50:34.614 Found 0 matching devices.                                                                                                               ble_connect.py:77
INFO     13:50:39.622    Discovered: GoPro 7501                                                                                                               ble_connect.py:73
INFO     13:50:39.625 Found 1 matching devices.                                                                                                               ble_connect.py:77
INFO     13:50:39.627 Establishing BLE connection to F4:76:4C:EB:72:D3: GoPro 7501...                                                                         ble_connect.py:82
INFO     13:50:40.332 BLE Connected!                                                                                                                          ble_connect.py:85
INFO     13:50:40.335 Attempting to pair...                                                                                                                   ble_connect.py:88
INFO     13:50:40.342 Pairing complete!                                                                                                                       ble_connect.py:94
INFO     13:50:40.344 Enabling notifications...                                                                                                               ble_connect.py:97
INFO     13:50:40.345 Enabling notification on char 00002a19-0000-1000-8000-00805f9b34fb                                                                     ble_connect.py:101
INFO     13:50:40.522 Enabling notification on char b5f90073-aa8d-11e3-9046-0002a5d5c51b                                                                     ble_connect.py:101
ERROR    13:50:40.643 Connection establishment failed: [WinError -2140864507] The attribute requires authentication before it can be read or written         ble_connect.py:108
WARNING  13:50:40.645 Retrying #0                                                                                                                            ble_connect.py:109

**Comment by tcamise-gpsw** [comment]
I just tested this exact setup and am seeing no issues.

The unfortunate truth is that the Python Windows Bleak interface is not robust depending on when / if you have reset / unpaired either device. So please try to start with a fresh connection state on each device as noted in the [troubleshooting section](https://gopro.github.io/OpenGoPro/tutorials/connect-ble#complete-system-reset)
