### ISSUE TITLE
How to test video preview stream 

### ISSUE THREAD

**Issue by ttakao** [gopro/OpenGoPro#557]
I'm try to use API 'Start Preview Stream'. On the API document, UDP data is provide from port 8556.
Data format is MPEG Transport Stream data MPEG2-TS.
I guess data souce might be;  10.5.5.9:8556 
But I cannot watch data on VCN or other streaming programs.
Could you tell me how do you test this API result ?

**Comment by tcamise-gpsw** [comment]
The Preview Stream is documented [here](https://gopro.github.io/OpenGoPro/http#tag/Preview-Stream)

Also the [Python SDK](https://gopro.github.io/OpenGoPro/python_sdk/index.html) includes a [demo](https://github.com/gopro/OpenGoPro/blob/main/demos/python/sdk_wireless_camera_control/open_gopro/demos/gui/preview_stream.py) showing the Preview Stream which uses `udp://127.0.0.1:{port}` where the port is configured from CLI input and defaults to 8554.

It looks like your main problem above is the port. As stated in the spec, the default port is 8554
