### ISSUE TITLE
Is there a way...to get the media list when recording has started by pressing record on the camera?

### ISSUE THREAD

**Issue by svanbodegraven** [gopro/OpenGoPro#572]
When starting recording by pressing record on the camera, calling gopro/media/list returns { "message": "Camera is busy" } with a status code of 503.

Is there a way via API or SDK to start recording via the camera and then querying the list of media and then download media?

Thanks.

**Comment by KonradIT** [comment]
Not while camera is recording or processing, as indicated by the json response.
