### ISSUE TITLE
GetHardwareInfo HTTP Spec Response Mismatch

### ISSUE THREAD

**Issue by mijoost** [gopro/OpenGoPro#581]
According to the API documentation (both, website and OpenAPI spec) /gopro/camera/info should return an info object.
However, with firmware H23.01.02.20.00 that info object level is omitted (items appear at top level).

```
curl --request GET --url "http://${CAMERAIPADDRESS}:8080/gopro/camera/info"

{
    "model_number": "62",
    "model_name": "HERO12 Black",
    "firmware_version": "H23.01.02.20.00",
    "serial_number": "C3501xxxxxxxxx",
    "ap_mac_addr": "xxxxxxxxxxxx",
    "ap_ssid": "GP25xxxxxx"
}

```

**Comment by tcamise-gpsw** [comment]
Good catch. I'll update the docs.

**Comment by tcamise-gpsw** [comment]
This has been fixed in the spec
