### ISSUE TITLE
Support Python 3.12 in Python SDK

### ISSUE THREAD

**Issue by a-finocchiaro** [gopro/OpenGoPro#588]
Hello! 

I'm not really sure if this should be submitted as a feature request or a bug, it's more of a general question. But I wanted to know if there are plans to release an updated version of the `open-gopro` python SDK for Python3.12? Currently the version that installs when using 3.12 is `0.9.2`.

Thanks!

**Comment by tcamise-gpsw** [comment]
Hello. I haven't yet tested on Python 3.12. I'll try to do this next week and assuming no issues will make a release with the rest of the [current ongoing maintenance](https://github.com/gopro/OpenGoPro/pull/569).

I don't anticipate any problems moving to 3.12 but we'll see.
