### ISSUE TITLE
COHN: Autoconnect to (last) network on camera start

### ISSUE THREAD

**Issue by demiantres** [gopro/OpenGoPro#598]
It would be useful to have an option to automatically let the GoPro camera connect to a Wi-Fi network on booting without having to put the camera into COHN state via Bluetooth first.

**Comment by tcamise-gpsw** [comment]
What you are requesting is already the current behavior. That is, if you provision COHN to a network the camera will auto-connect to this network on camera start.

I just looked at the docs and this does not seem obvious. We need to do a significant review of COHN documentation / tutorials.
