### ISSUE TITLE
Support preview stream in COHN mode

### ISSUE THREAD

**Issue by demiantres** [gopro/OpenGoPro#601]
Live preview support in COHN mode would be nice.

**Comment by tcamise-gpsw** [comment]
This is already possible. I just tested to verify. Just:
1. Provision COHN
2. Send [Preview Start HTTP operation](https://gopro.github.io/OpenGoPro/http#tag/Preview-Stream/operation/OGP_PREVIEW_STREAM_START)
3. View preview stream in VLC
