### ISSUE TITLE
problem with download media file

### ISSUE THREAD

**Issue by OPEC239** [gopro/OpenGoPro#610]
Hi gus, having an issue here and has no clue when I try to download a media file from gopro
import requests
url = "http://172.29.141.51:8080/videos/DCIM/100GOPRO/GX010519.MP4"
response = requests.request("GET", url)
print(response.text)

When I use the above code python just crashed. I was wondering where will this file save to, because there is no directry input to let the gopro know where to save the file, e.g d:/goprofiles/ something like that.

Thanks for the help.

**Comment by KonradIT** [comment]
That's not really OpenGoPro related, you need to change the `requests` response to bytes and save it. Lots of tutorials online.
