### ISSUE TITLE
Hero 4K: /gp/gpMediaList crashes camera under certain conditions

### ISSUE THREAD

**Issue by demiantres** [gopro/OpenGoPro#617]
Executing "/gp/gpMediaList" on the Hero 4k/2024 crashes the camera when the SD card contains media files which were not recorded by the camera. For instance, if you put a SD card into the camera which contains videos/photos previously recorded with the GoPro Hero 13 then the camera will crash.

**Comment by bfreeland-gpsw** [comment]
Open GoPro is currently unsupported on Hero 4K/2024. Support will be added in a later firmware.

**Comment by demiantres** [comment]
Just a side note: This problem is independent from Open GoPro (the camera also crashes when using the on-device media browser or the Quik).
