### ISSUE TITLE
Questions about streaming

### ISSUE THREAD

**Issue by sunwonlikeyou** [gopro/OpenGoPro#72]
I'd like to make streaming service with wireless.
So  I want to know transfer speed of wifi and bluetooth.
And also received image type - jpg? or mp4? raw?
Does it only send images to url??

**Comment by tcamise-gpsw** [comment]
Hello. This control is at a layer below the Open GoPro SDK and, at least for Bluetooth, is dependent on your computer (or whatever peer device you are using).

To summarize, you should (and only can) use WiFi for streaming. The throughput is at least good enough to work with the official GoPro Quik app.

**Comment by tcamise-gpsw** [comment]
In terms of image format, you can choose either .jpg and / or raw (.gpr).

Here is a pretty good summary: https://havecamerawilltravel.com/gopro/photos-jpg-vs-raw-gpr/

**Comment by tcamise-gpsw** [comment]
Closing since there are no actions to take.
