### ISSUE TITLE
Wifi command: 404 Not Found

### ISSUE THREAD

**Issue by tqloc0311** [gopro/OpenGoPro#75]
**Component**
Wifi command

**Describe the bug**
I got the "404 Not Found Not Found" error when sending any wifi command.
ex: http://10.5.5.9:8080/gopro/camera/digital_zoom?percent=50

it works properly with goprowifihack
ex: http://10.5.5.9/gp/gpControl/command/digital_zoom?range_pcnt=50

Please help!

**Hardware**
- Camera: Hero9

**Comment by tcamise-gpsw** [comment]
I assume you are using a Hero 9. If so, the minimum supported version is [1.60](https://gopro.github.io/OpenGoPro/wifi_1_0#supported-cameras)
