### ISSUE TITLE
It can not pair to hero 10

### ISSUE THREAD

**Issue by zsinba** [gopro/OpenGoPro#76]
**Component**
What is the bug in? 
- Demos (python sdk, etc) 
- Tutorials
- Documentation
- Specs (ble , wifi)

**Describe the bug**

**To Reproduce**
C#&Swift
Run it and scan , get the list and pair it . the C# and Swift Demo can not pair the hero 10.
![image](https://user-images.githubusercontent.com/890157/137891685-372abf99-5a79-4657-abf9-d04f148311ed.png)

**Expected behavior**

**Screenshots**

**Hardware**
- Camera: Hero9, etc.
- Desktop if applicable [e.g. Windows] 
- Smartphone if applicable [e.g. iPhone6]

**Additional context**

**Comment by tcamise-gpsw** [comment]
Hi. First, make sure you computer is not already connected to the camera. This is usually the problem.

If it is not, you can try resetting the pairing info on both sides. 
So, on the camera:
- Connections --> Reset Connections
On your computer, you need to forget / unpair / remove the camera from your Bluetooth settings

**Comment by zsinba** [comment]
> Hi. First, make sure you computer is not already connected to the camera. This is usually the problem.
> 
> If it is not, you can try resetting the pairing info on both sides. So, on the camera, do: Connections --> Reset Connections On your computer, you need to forget / unpair / remove the camera from your Bluetooth settings

Thank you very much. I connected it just now.
the Pair operation should be op once. I have a mistake  that the pair should operate by the mobile phone quik app.

ps:
Can I send the SSID & password to the GoPro hero10,and start streaming live by the ble command?

**Comment by fypsoftware39** [comment]
How do you get your gopro 9 to be connected using the BLE tutorial? I cant find the gopro 9 device on my bluetooth devices.
