### ISSUE TITLE
What is the maximum number of cameras supported at one time?

### ISSUE THREAD

**Issue by gmoneyphx** [gopro/OpenGoPro#83]
Is it possible to start/stop 32 cameras at one time?  This would be using the Python SDK specifically.  I realize to download media I will have to go through and connect/disconnect to each camera individually.

**Comment by tcamise-gpsw** [comment]
Yep, the Python SDK is designed to be scalable at least for the BLE connections. So yes you can create GoPro instances for each of the cameras and connect / disconnect as mentioned above. The only limitations I can think of are:
- your computer's memory. This should not be an issue
- BLE over-the-air bandwidth. This could potentially be an issue and you may thus see some latency. If we consider the Bluetooth spec-defined minimum connection interval of 10 ms, then the minimum latency to do this is 32 * 10 ms = 320 ms. However, the connection interval depends on what your computer's Bluetooth controller supports and is almost certainly higher than 10 ms. Coupled with RF interference and I wouldn't be surprised to see around second latency.

**Comment by tcamise-gpsw** [comment]
Closing since there is nothing currently preventing this.
