### ISSUE TITLE
Camera fails to pair with Raspberry Pi

### ISSUE THREAD

**Issue by kevinlieb** [gopro/OpenGoPro#85]
GoPro 10 camera

I am trying to test out the Python libraries on a Raspberry Pi 3 and having no luck.

From the most basic level I am trying:

sudo bluetoothctl
agent on

trust FE:F5:AC:77:17:27
responds: Changing FE:F5:AC:77:17:27 trust succeeded

pair FE:F5:AC:77:17:27

and I get:
Device FE:F5:AC:77:17:27 Connected: yes
Failed to pair: org.bluez.Error.ConnectionAttemptFailed
[CHG] Device FE:F5:AC:77:17:27 Connected: no

On the gopro-photo demo I get:
17:19:29.751 Found 1 matching devices.                                         bleak_wrapper.py:151
INFO     17:19:29.763 Establishing BLE connection to FE:F5:AC:77:17:27: GoPro 9745...   bleak_wrapper.py:178
ERROR    17:19:30.752 Ble connection terminated unexpectedly.                                   gopro.py:549
ERROR    17:19:30.765 Failed to remove match InterfacesAdded                                   client.py:391
         (/org/bluez/hci0/dev_FE_F5_AC_77_17_27):
ERROR    17:19:30.779 Failed to remove match InterfacesRemoved                                 client.py:391
         (/org/bluez/hci0/dev_FE_F5_AC_77_17_27): 'NoneType' object has no attribute 'call'
ERROR    17:19:30.793 Failed to remove match PropertiesChanged                                 client.py:391
         (/org/bluez/hci0/dev_FE_F5_AC_77_17_27): 'NoneType' object has no attribute 'call'
WARNING  17:19:30.806 Bleak failed to connect: BleakDBusError('org.bluez.Error.Failed', bleak_wrapper.py:183
         'Software caused connection abort')

Any idea what I am doing wrong?

**Comment by tcamise-gpsw** [comment]
Hello. Have you tried following the bash tutorial: https://gopro.github.io/OpenGoPro/tutorials/bash/bluez

That should at least work for Ubuntu.
