### ISSUE TITLE
Documentation:  BLE Characteristics permission not correct

### ISSUE THREAD

**Issue by XHMM** [gopro/OpenGoPro#87]
**Component**
What is the bug in? 
- Documentation

**Describe the bug**
here [doc](https://gopro.github.io/OpenGoPro/ble_2_0#services-and-characteristics)  said `GP-0005` has `read/notify `permission, but I tested with my gopro10black, it's `read/indicate`

docs:
![image](https://user-images.githubusercontent.com/24786522/140642415-86546b27-aea4-4e18-bf44-86f52a5bc093.png)

my results:
![image](https://user-images.githubusercontent.com/24786522/140642474-50b6de80-bdeb-4a75-8333-2052848e5f32.png)

**To Reproduce**
connect to you gopro10black with some BLE debug tools to view

**Hardware**
- Camera: Hero10 black

**Comment by tcamise-gpsw** [comment]
Thanks for pointing this out. I will update this.

**Comment by tcamise-gpsw** [comment]
Hi. This is fixed in the latest [docs](https://gopro.github.io/OpenGoPro/ble_2_0#services-and-characteristics):
