### ISSUE TITLE
Set date/time (missing?)

### ISSUE THREAD

**Issue by developer-appdam** [gopro/OpenGoPro#91]
Hi,

I keep trying to read the documentation where it states that it's possible to set the date/time but I really don't see how to set the date/time. Is this actually possible? And if so, how can we set the date/time of the GoPro through the API? Everything that I can see so far are just GET calls.

Thanks

**Comment by KonradIT** [comment]
True, needs to be added to this wiki.

It's specified in the unofficial docs: https://github.com/KonradIT/goprowifihack/blob/master/Bluetooth/bluetooth-api.md#command-requests

**Comment by tcamise-gpsw** [comment]
Hello. Yeah, we should not have mentioned it without the API documented. In terms of official support, it is coming soon. That is:
1. A new open gopro endpoint will be added to set time via WiFi
2. Documentation will be added to show how to set time via BLE

**Comment by developer-appdam** [comment]
Perfect! For now, I will try to implement the current "unofficial" method

**Comment by tcamise-gpsw** [comment]
Hi. This has been added in the latest firmware release / documentation. Note that the datetime status has been removed. So now there are datetime get and set commands for both BLE and HTTP.
